import type { PhonicsLessonData, LetterData } from './phonicsLessons';

export const CONSONANT_BLEND_LESSONS: PhonicsLessonData[] = [
  {
    id: 'blend_bl_br',
    title: 'Blends: BL & BR',
    titleRu: 'Сочетания: BL и BR',
    letters: [
      { letter: 'bl', sound: '/bl/', word: 'blue', wordRu: 'синий', emoji: '💙' },
      { letter: 'bl', sound: '/bl/', word: 'black', wordRu: 'чёрный', emoji: '⬛' },
      { letter: 'br', sound: '/br/', word: 'brown', wordRu: 'коричневый', emoji: '🤎' },
      { letter: 'br', sound: '/br/', word: 'bread', wordRu: 'хлеб', emoji: '🍞' },
    ],
    practiceWords: [
      { word: 'black', ru: 'чёрный', emoji: '⬛' },
      { word: 'blue', ru: 'синий', emoji: '💙' },
      { word: 'block', ru: 'блок', emoji: '🧱' },
      { word: 'blow', ru: 'дуть', emoji: '💨' },
      { word: 'blink', ru: 'моргать', emoji: '😉' },
      { word: 'brown', ru: 'коричневый', emoji: '🤎' },
      { word: 'bread', ru: 'хлеб', emoji: '🍞' },
      { word: 'bring', ru: 'приносить', emoji: '🤲' },
      { word: 'brush', ru: 'щётка', emoji: '🪥' },
      { word: 'brave', ru: 'смелый', emoji: '🦁' },
    ],
  },
  {
    id: 'blend_cl_cr',
    title: 'Blends: CL & CR',
    titleRu: 'Сочетания: CL и CR',
    letters: [
      { letter: 'cl', sound: '/kl/', word: 'clap', wordRu: 'хлопать', emoji: '👏' },
      { letter: 'cl', sound: '/kl/', word: 'clock', wordRu: 'часы', emoji: '🕐' },
      { letter: 'cr', sound: '/kr/', word: 'crab', wordRu: 'краб', emoji: '🦀' },
      { letter: 'cr', sound: '/kr/', word: 'crown', wordRu: 'корона', emoji: '👑' },
    ],
    practiceWords: [
      { word: 'clap', ru: 'хлопать', emoji: '👏' },
      { word: 'clip', ru: 'зажим', emoji: '📎' },
      { word: 'clock', ru: 'часы', emoji: '🕐' },
      { word: 'close', ru: 'закрывать', emoji: '🚪' },
      { word: 'club', ru: 'клуб', emoji: '🏠' },
      { word: 'crab', ru: 'краб', emoji: '🦀' },
      { word: 'cry', ru: 'плакать', emoji: '😢' },
      { word: 'cross', ru: 'крест', emoji: '✝️' },
      { word: 'crown', ru: 'корона', emoji: '👑' },
      { word: 'crush', ru: 'давить', emoji: '💥' },
    ],
  },
  {
    id: 'blend_dr_fl',
    title: 'Blends: DR & FL',
    titleRu: 'Сочетания: DR и FL',
    letters: [
      { letter: 'dr', sound: '/dr/', word: 'drum', wordRu: 'барабан', emoji: '🥁' },
      { letter: 'dr', sound: '/dr/', word: 'dress', wordRu: 'платье', emoji: '👗' },
      { letter: 'fl', sound: '/fl/', word: 'flag', wordRu: 'флаг', emoji: '🏳️' },
      { letter: 'fl', sound: '/fl/', word: 'flower', wordRu: 'цветок', emoji: '🌸' },
    ],
    practiceWords: [
      { word: 'dress', ru: 'платье', emoji: '👗' },
      { word: 'drink', ru: 'пить', emoji: '🥤' },
      { word: 'drop', ru: 'капля', emoji: '💧' },
      { word: 'drum', ru: 'барабан', emoji: '🥁' },
      { word: 'draw', ru: 'рисовать', emoji: '✏️' },
      { word: 'flag', ru: 'флаг', emoji: '🚩' },
      { word: 'flat', ru: 'плоский', emoji: '📏' },
      { word: 'flip', ru: 'переворот', emoji: '🔄' },
      { word: 'fly', ru: 'летать', emoji: '🪰' },
      { word: 'flower', ru: 'цветок', emoji: '🌸' },
    ],
  },
  {
    id: 'blend_fr_gl',
    title: 'Blends: FR & GL',
    titleRu: 'Сочетания: FR и GL',
    letters: [
      { letter: 'fr', sound: '/fr/', word: 'frog', wordRu: 'лягушка', emoji: '🐸' },
      { letter: 'fr', sound: '/fr/', word: 'fruit', wordRu: 'фрукт', emoji: '🍎' },
      { letter: 'gl', sound: '/gl/', word: 'globe', wordRu: 'глобус', emoji: '🌍' },
      { letter: 'gl', sound: '/gl/', word: 'glass', wordRu: 'стакан', emoji: '🥛' },
    ],
    practiceWords: [
      { word: 'frog', ru: 'лягушка', emoji: '🐸' },
      { word: 'free', ru: 'свободный', emoji: '🕊️' },
      { word: 'from', ru: 'от', emoji: '➡️' },
      { word: 'fruit', ru: 'фрукт', emoji: '🍎' },
      { word: 'fresh', ru: 'свежий', emoji: '🌿' },
      { word: 'glad', ru: 'рад', emoji: '😊' },
      { word: 'glass', ru: 'стакан', emoji: '🥛' },
      { word: 'glow', ru: 'сияние', emoji: '✨' },
      { word: 'glue', ru: 'клей', emoji: '🧴' },
      { word: 'globe', ru: 'глобус', emoji: '🌍' },
    ],
  },
  {
    id: 'blend_gr_pl',
    title: 'Blends: GR & PL',
    titleRu: 'Сочетания: GR и PL',
    letters: [
      { letter: 'gr', sound: '/gr/', word: 'green', wordRu: 'зелёный', emoji: '💚' },
      { letter: 'gr', sound: '/gr/', word: 'grape', wordRu: 'виноград', emoji: '🍇' },
      { letter: 'pl', sound: '/pl/', word: 'play', wordRu: 'играть', emoji: '🎮' },
      { letter: 'pl', sound: '/pl/', word: 'plant', wordRu: 'растение', emoji: '🪴' },
    ],
    practiceWords: [
      { word: 'green', ru: 'зелёный', emoji: '💚' },
      { word: 'grass', ru: 'трава', emoji: '🌱' },
      { word: 'grow', ru: 'расти', emoji: '🌱' },
      { word: 'grape', ru: 'виноград', emoji: '🍇' },
      { word: 'gray', ru: 'серый', emoji: '🩶' },
      { word: 'play', ru: 'играть', emoji: '🎮' },
      { word: 'plan', ru: 'план', emoji: '📋' },
      { word: 'plant', ru: 'растение', emoji: '🪴' },
      { word: 'plate', ru: 'тарелка', emoji: '🍽️' },
      { word: 'plum', ru: 'слива', emoji: '🫐' },
    ],
  },
  {
    id: 'blend_pr_sl',
    title: 'Blends: PR & SL',
    titleRu: 'Сочетания: PR и SL',
    letters: [
      { letter: 'pr', sound: '/pr/', word: 'prize', wordRu: 'приз', emoji: '🏆' },
      { letter: 'pr', sound: '/pr/', word: 'print', wordRu: 'печатать', emoji: '🖨️' },
      { letter: 'sl', sound: '/sl/', word: 'sleep', wordRu: 'спать', emoji: '😴' },
      { letter: 'sl', sound: '/sl/', word: 'slow', wordRu: 'медленный', emoji: '🐢' },
    ],
    practiceWords: [
      { word: 'press', ru: 'нажимать', emoji: '🔘' },
      { word: 'print', ru: 'печатать', emoji: '🖨️' },
      { word: 'prize', ru: 'приз', emoji: '🏆' },
      { word: 'pretty', ru: 'красивый', emoji: '🌺' },
      { word: 'pray', ru: 'молиться', emoji: '🙏' },
      { word: 'slim', ru: 'стройный', emoji: '🧍' },
      { word: 'slip', ru: 'скользить', emoji: '🛝' },
      { word: 'slow', ru: 'медленный', emoji: '🐢' },
      { word: 'sleep', ru: 'спать', emoji: '😴' },
      { word: 'slide', ru: 'горка', emoji: '🛝' },
    ],
  },
  {
    id: 'blend_sm_sn',
    title: 'Blends: SM & SN',
    titleRu: 'Сочетания: SM и SN',
    letters: [
      { letter: 'sm', sound: '/sm/', word: 'smile', wordRu: 'улыбка', emoji: '😊' },
      { letter: 'sm', sound: '/sm/', word: 'small', wordRu: 'маленький', emoji: '🐜' },
      { letter: 'sn', sound: '/sn/', word: 'snake', wordRu: 'змея', emoji: '🐍' },
      { letter: 'sn', sound: '/sn/', word: 'snow', wordRu: 'снег', emoji: '❄️' },
    ],
    practiceWords: [
      { word: 'small', ru: 'маленький', emoji: '🐜' },
      { word: 'smell', ru: 'запах', emoji: '👃' },
      { word: 'smile', ru: 'улыбка', emoji: '😊' },
      { word: 'smoke', ru: 'дым', emoji: '💨' },
      { word: 'smart', ru: 'умный', emoji: '🧠' },
      { word: 'snap', ru: 'щёлкать', emoji: '🫰' },
      { word: 'snip', ru: 'стричь', emoji: '✂️' },
      { word: 'snow', ru: 'снег', emoji: '❄️' },
      { word: 'snake', ru: 'змея', emoji: '🐍' },
      { word: 'snack', ru: 'перекус', emoji: '🍿' },
    ],
  },
  {
    id: 'blend_sp_st',
    title: 'Blends: SP & ST',
    titleRu: 'Сочетания: SP и ST',
    letters: [
      { letter: 'sp', sound: '/sp/', word: 'spoon', wordRu: 'ложка', emoji: '🥄' },
      { letter: 'sp', sound: '/sp/', word: 'space', wordRu: 'космос', emoji: '🚀' },
      { letter: 'st', sound: '/st/', word: 'star', wordRu: 'звезда', emoji: '⭐' },
      { letter: 'st', sound: '/st/', word: 'stop', wordRu: 'стоп', emoji: '🛑' },
    ],
    practiceWords: [
      { word: 'spin', ru: 'вращать', emoji: '🌀' },
      { word: 'spot', ru: 'пятно', emoji: '🔴' },
      { word: 'spell', ru: 'заклинание', emoji: '🪄' },
      { word: 'spoon', ru: 'ложка', emoji: '🥄' },
      { word: 'space', ru: 'космос', emoji: '🚀' },
      { word: 'stop', ru: 'стоп', emoji: '🛑' },
      { word: 'star', ru: 'звезда', emoji: '⭐' },
      { word: 'step', ru: 'шаг', emoji: '👣' },
      { word: 'stick', ru: 'палка', emoji: '🪵' },
      { word: 'stone', ru: 'камень', emoji: '🪨' },
    ],
  },
  {
    id: 'blend_sw_tr',
    title: 'Blends: SW & TR',
    titleRu: 'Сочетания: SW и TR',
    letters: [
      { letter: 'sw', sound: '/sw/', word: 'swim', wordRu: 'плавать', emoji: '🏊' },
      { letter: 'sw', sound: '/sw/', word: 'sweet', wordRu: 'сладкий', emoji: '🍬' },
      { letter: 'tr', sound: '/tr/', word: 'tree', wordRu: 'дерево', emoji: '🌳' },
      { letter: 'tr', sound: '/tr/', word: 'train', wordRu: 'поезд', emoji: '🚂' },
    ],
    practiceWords: [
      { word: 'swim', ru: 'плавать', emoji: '🏊' },
      { word: 'sweet', ru: 'сладкий', emoji: '🍬' },
      { word: 'swing', ru: 'качели', emoji: '🎠' },
      { word: 'switch', ru: 'переключатель', emoji: '🔀' },
      { word: 'sweep', ru: 'подметать', emoji: '🧹' },
      { word: 'tree', ru: 'дерево', emoji: '🌳' },
      { word: 'trip', ru: 'поездка', emoji: '🧳' },
      { word: 'truck', ru: 'грузовик', emoji: '🚛' },
      { word: 'train', ru: 'поезд', emoji: '🚂' },
      { word: 'trap', ru: 'ловушка', emoji: '🪤' },
    ],
  },
];
