import type { PhonicsLessonData } from './phonicsLessons';

export const DIGRAPH_LESSONS: PhonicsLessonData[] = [
  {
    id: 'digraph_sh',
    title: 'Digraph SH',
    titleRu: 'Буквосочетание SH',
    letters: [
      { letter: 'sh', sound: '/ʃ/', word: 'ship', wordRu: 'корабль', emoji: '🚢' },
      { letter: 'sh', sound: '/ʃ/', word: 'fish', wordRu: 'рыба', emoji: '🐟' },
      { letter: 'sh', sound: '/ʃ/', word: 'shoe', wordRu: 'ботинок', emoji: '👟' },
      { letter: 'sh', sound: '/ʃ/', word: 'shell', wordRu: 'ракушка', emoji: '🐚' },
    ],
    practiceWords: [
      { word: 'ship', ru: 'корабль', emoji: '🚢' },
      { word: 'shop', ru: 'магазин', emoji: '🏪' },
      { word: 'fish', ru: 'рыба', emoji: '🐟' },
      { word: 'dish', ru: 'тарелка', emoji: '🍽️' },
      { word: 'shell', ru: 'ракушка', emoji: '🐚' },
      { word: 'shoe', ru: 'ботинок', emoji: '👟' },
      { word: 'she', ru: 'она', emoji: '👩' },
      { word: 'shut', ru: 'закрыть', emoji: '🚪' },
      { word: 'wish', ru: 'желание', emoji: '🌠' },
      { word: 'push', ru: 'толкать', emoji: '🫸' },
    ],
  },
  {
    id: 'digraph_ch',
    title: 'Digraph CH',
    titleRu: 'Буквосочетание CH',
    letters: [
      { letter: 'ch', sound: '/tʃ/', word: 'chip', wordRu: 'чипсина', emoji: '🍟' },
      { letter: 'ch', sound: '/tʃ/', word: 'cheese', wordRu: 'сыр', emoji: '🧀' },
      { letter: 'ch', sound: '/tʃ/', word: 'lunch', wordRu: 'обед', emoji: '🍱' },
      { letter: 'ch', sound: '/tʃ/', word: 'check', wordRu: 'проверить', emoji: '✅' },
    ],
    practiceWords: [
      { word: 'chip', ru: 'чипсина', emoji: '🍟' },
      { word: 'chat', ru: 'болтать', emoji: '💬' },
      { word: 'chin', ru: 'подбородок', emoji: '🧔' },
      { word: 'chop', ru: 'рубить', emoji: '🪓' },
      { word: 'much', ru: 'много', emoji: '📦' },
      { word: 'such', ru: 'такой', emoji: '👆' },
      { word: 'rich', ru: 'богатый', emoji: '💰' },
      { word: 'check', ru: 'проверить', emoji: '✅' },
      { word: 'chest', ru: 'сундук', emoji: '🧳' },
      { word: 'lunch', ru: 'обед', emoji: '🍱' },
    ],
  },
  {
    id: 'digraph_th',
    title: 'Digraph TH',
    titleRu: 'Буквосочетание TH',
    letters: [
      { letter: 'th', sound: '/θ/', word: 'three', wordRu: 'три', emoji: '3️⃣' },
      { letter: 'th', sound: '/θ/', word: 'thin', wordRu: 'тонкий', emoji: '🔍' },
      { letter: 'th', sound: '/θ/', word: 'bath', wordRu: 'ванна', emoji: '🛁' },
      { letter: 'th', sound: '/θ/', word: 'math', wordRu: 'математика', emoji: '➕' },
    ],
    practiceWords: [
      { word: 'this', ru: 'это', emoji: '👉' },
      { word: 'that', ru: 'тот', emoji: '👈' },
      { word: 'the', ru: 'определённый артикль', emoji: '📌' },
      { word: 'them', ru: 'им/их', emoji: '👥' },
      { word: 'then', ru: 'тогда', emoji: '➡️' },
      { word: 'thin', ru: 'тонкий', emoji: '📏' },
      { word: 'thick', ru: 'толстый', emoji: '🧱' },
      { word: 'three', ru: 'три', emoji: '3️⃣' },
      { word: 'bath', ru: 'ванна', emoji: '🛁' },
      { word: 'math', ru: 'математика', emoji: '🧮' },
    ],
  },
  {
    id: 'digraph_wh',
    title: 'Digraph WH',
    titleRu: 'Буквосочетание WH',
    letters: [
      { letter: 'wh', sound: '/w/', word: 'what', wordRu: 'что', emoji: '❓' },
      { letter: 'wh', sound: '/w/', word: 'when', wordRu: 'когда', emoji: '⏰' },
      { letter: 'wh', sound: '/w/', word: 'where', wordRu: 'где', emoji: '📍' },
      { letter: 'wh', sound: '/w/', word: 'whale', wordRu: 'кит', emoji: '🐋' },
    ],
    practiceWords: [
      { word: 'what', ru: 'что', emoji: '❓' },
      { word: 'when', ru: 'когда', emoji: '🕐' },
      { word: 'where', ru: 'где', emoji: '📍' },
      { word: 'which', ru: 'который', emoji: '🔀' },
      { word: 'white', ru: 'белый', emoji: '⬜' },
      { word: 'while', ru: 'пока', emoji: '⏳' },
      { word: 'whale', ru: 'кит', emoji: '🐋' },
      { word: 'wheel', ru: 'колесо', emoji: '🛞' },
      { word: 'whip', ru: 'кнут', emoji: '🏇' },
      { word: 'why', ru: 'почему', emoji: '🤔' },
    ],
  },
  {
    id: 'digraph_ph',
    title: 'Digraph PH',
    titleRu: 'Буквосочетание PH',
    letters: [
      { letter: 'ph', sound: '/f/', word: 'phone', wordRu: 'телефон', emoji: '📱' },
      { letter: 'ph', sound: '/f/', word: 'photo', wordRu: 'фото', emoji: '📸' },
      { letter: 'ph', sound: '/f/', word: 'elephant', wordRu: 'слон', emoji: '🐘' },
      { letter: 'ph', sound: '/f/', word: 'dolphin', wordRu: 'дельфин', emoji: '🐬' },
    ],
    practiceWords: [
      { word: 'phone', ru: 'телефон', emoji: '📱' },
      { word: 'photo', ru: 'фото', emoji: '📸' },
      { word: 'Phil', ru: 'Фил (имя)', emoji: '👦' },
      { word: 'phrase', ru: 'фраза', emoji: '💬' },
      { word: 'elephant', ru: 'слон', emoji: '🐘' },
      { word: 'dolphin', ru: 'дельфин', emoji: '🐬' },
      { word: 'graph', ru: 'график', emoji: '📊' },
      { word: 'alphabet', ru: 'алфавит', emoji: '🔤' },
      { word: 'trophy', ru: 'трофей', emoji: '🏆' },
      { word: 'pharmacy', ru: 'аптека', emoji: '💊' },
    ],
  },
  {
    id: 'digraph_ck',
    title: 'Digraph CK',
    titleRu: 'Буквосочетание CK',
    letters: [
      { letter: 'ck', sound: '/k/', word: 'clock', wordRu: 'часы', emoji: '🕐' },
      { letter: 'ck', sound: '/k/', word: 'duck', wordRu: 'утка', emoji: '🦆' },
      { letter: 'ck', sound: '/k/', word: 'sock', wordRu: 'носок', emoji: '🧦' },
      { letter: 'ck', sound: '/k/', word: 'kick', wordRu: 'пинать', emoji: '⚽' },
    ],
    practiceWords: [
      { word: 'back', ru: 'назад', emoji: '🔙' },
      { word: 'black', ru: 'чёрный', emoji: '⬛' },
      { word: 'clock', ru: 'часы', emoji: '🕐' },
      { word: 'duck', ru: 'утка', emoji: '🦆' },
      { word: 'kick', ru: 'пинать', emoji: '🦶' },
      { word: 'lock', ru: 'замок', emoji: '🔒' },
      { word: 'neck', ru: 'шея', emoji: '🦒' },
      { word: 'rock', ru: 'скала', emoji: '🪨' },
      { word: 'sick', ru: 'больной', emoji: '🤒' },
      { word: 'sock', ru: 'носок', emoji: '🧦' },
    ],
  },
  {
    id: 'digraph_ng',
    title: 'Digraph NG',
    titleRu: 'Буквосочетание NG',
    letters: [
      { letter: 'ng', sound: '/ŋ/', word: 'sing', wordRu: 'петь', emoji: '🎤' },
      { letter: 'ng', sound: '/ŋ/', word: 'ring', wordRu: 'кольцо', emoji: '💍' },
      { letter: 'ng', sound: '/ŋ/', word: 'king', wordRu: 'король', emoji: '👑' },
      { letter: 'ng', sound: '/ŋ/', word: 'wing', wordRu: 'крыло', emoji: '🪽' },
    ],
    practiceWords: [
      { word: 'sing', ru: 'петь', emoji: '🎤' },
      { word: 'ring', ru: 'кольцо', emoji: '💍' },
      { word: 'king', ru: 'король', emoji: '👑' },
      { word: 'long', ru: 'длинный', emoji: '📏' },
      { word: 'song', ru: 'песня', emoji: '🎵' },
      { word: 'thing', ru: 'вещь', emoji: '📦' },
      { word: 'bring', ru: 'принести', emoji: '🤲' },
      { word: 'wing', ru: 'крыло', emoji: '🪽' },
      { word: 'bang', ru: 'хлопок', emoji: '💥' },
      { word: 'hung', ru: 'повесил', emoji: '🪝' },
    ],
  },
];
