import type { PhonicsLessonData } from './phonicsLessons';

export const VOWEL_TEAM_LESSONS: PhonicsLessonData[] = [
  {
    id: 'vt_ee',
    title: 'Vowel Team EE',
    titleRu: 'Сочетание EE — /iː/',
    letters: [
      { letter: 'ee', sound: '/iː/', word: 'tree', wordRu: 'дерево', emoji: '🌳' },
      { letter: 'ee', sound: '/iː/', word: 'bee', wordRu: 'пчела', emoji: '🐝' },
      { letter: 'ee', sound: '/iː/', word: 'green', wordRu: 'зелёный', emoji: '🟢' },
      { letter: 'ee', sound: '/iː/', word: 'sheep', wordRu: 'овца', emoji: '🐑' },
    ],
    practiceWords: [
      { word: 'tree', ru: 'дерево', emoji: '🌳' },
      { word: 'free', ru: 'свободный', emoji: '🕊️' },
      { word: 'three', ru: 'три', emoji: '3️⃣' },
      { word: 'see', ru: 'видеть', emoji: '👀' },
      { word: 'bee', ru: 'пчела', emoji: '🐝' },
      { word: 'green', ru: 'зелёный', emoji: '💚' },
      { word: 'feet', ru: 'ноги', emoji: '🦶' },
      { word: 'sleep', ru: 'спать', emoji: '😴' },
      { word: 'sheep', ru: 'овца', emoji: '🐑' },
      { word: 'week', ru: 'неделя', emoji: '📅' },
    ],
  },
  {
    id: 'vt_ea',
    title: 'Vowel Team EA',
    titleRu: 'Сочетание EA — /iː/',
    letters: [
      { letter: 'ea', sound: '/iː/', word: 'sea', wordRu: 'море', emoji: '🌊' },
      { letter: 'ea', sound: '/iː/', word: 'tea', wordRu: 'чай', emoji: '🍵' },
      { letter: 'ea', sound: '/iː/', word: 'beach', wordRu: 'пляж', emoji: '🏖️' },
      { letter: 'ea', sound: '/iː/', word: 'eat', wordRu: 'есть', emoji: '🍽️' },
    ],
    practiceWords: [
      { word: 'sea', ru: 'море', emoji: '🌊' },
      { word: 'tea', ru: 'чай', emoji: '🍵' },
      { word: 'eat', ru: 'есть', emoji: '🍽️' },
      { word: 'read', ru: 'читать', emoji: '📖' },
      { word: 'meat', ru: 'мясо', emoji: '🥩' },
      { word: 'bean', ru: 'фасоль', emoji: '🫘' },
      { word: 'team', ru: 'команда', emoji: '👥' },
      { word: 'clean', ru: 'чистый', emoji: '✨' },
      { word: 'dream', ru: 'мечта', emoji: '💭' },
      { word: 'beach', ru: 'пляж', emoji: '🏖️' },
    ],
  },
  {
    id: 'vt_ai_ay',
    title: 'Vowel Teams AI & AY',
    titleRu: 'Сочетания AI и AY — /eɪ/',
    letters: [
      { letter: 'ai', sound: '/eɪ/', word: 'rain', wordRu: 'дождь', emoji: '🌧️' },
      { letter: 'ai', sound: '/eɪ/', word: 'train', wordRu: 'поезд', emoji: '🚂' },
      { letter: 'ay', sound: '/eɪ/', word: 'play', wordRu: 'играть', emoji: '🎮' },
      { letter: 'ay', sound: '/eɪ/', word: 'day', wordRu: 'день', emoji: '📅' },
    ],
    practiceWords: [
      { word: 'rain', ru: 'дождь', emoji: '🌧️' },
      { word: 'train', ru: 'поезд', emoji: '🚂' },
      { word: 'wait', ru: 'ждать', emoji: '⏳' },
      { word: 'paint', ru: 'краска', emoji: '🎨' },
      { word: 'tail', ru: 'хвост', emoji: '🐕' },
      { word: 'play', ru: 'играть', emoji: '🎮' },
      { word: 'day', ru: 'день', emoji: '☀️' },
      { word: 'say', ru: 'сказать', emoji: '💬' },
      { word: 'way', ru: 'путь', emoji: '🛤️' },
      { word: 'stay', ru: 'оставаться', emoji: '🏠' },
    ],
  },
  {
    id: 'vt_oa',
    title: 'Vowel Team OA',
    titleRu: 'Сочетание OA — /oʊ/',
    letters: [
      { letter: 'oa', sound: '/oʊ/', word: 'boat', wordRu: 'лодка', emoji: '⛵' },
      { letter: 'oa', sound: '/oʊ/', word: 'coat', wordRu: 'пальто', emoji: '🧥' },
      { letter: 'oa', sound: '/oʊ/', word: 'road', wordRu: 'дорога', emoji: '🛣️' },
      { letter: 'oa', sound: '/oʊ/', word: 'toast', wordRu: 'тост', emoji: '🥪' },
    ],
    practiceWords: [
      { word: 'boat', ru: 'лодка', emoji: '⛵' },
      { word: 'coat', ru: 'пальто', emoji: '🧥' },
      { word: 'road', ru: 'дорога', emoji: '🛣️' },
      { word: 'load', ru: 'груз', emoji: '📦' },
      { word: 'soap', ru: 'мыло', emoji: '🧼' },
      { word: 'oak', ru: 'дуб', emoji: '🌳' },
      { word: 'goal', ru: 'гол', emoji: '⚽' },
      { word: 'toast', ru: 'тост', emoji: '🍞' },
      { word: 'foam', ru: 'пена', emoji: '🫧' },
      { word: 'toad', ru: 'жаба', emoji: '🐸' },
    ],
  },
  {
    id: 'vt_oo',
    title: 'Vowel Team OO',
    titleRu: 'Сочетание OO — /uː/',
    letters: [
      { letter: 'oo', sound: '/uː/', word: 'moon', wordRu: 'луна', emoji: '🌙' },
      { letter: 'oo', sound: '/uː/', word: 'zoo', wordRu: 'зоопарк', emoji: '🦁' },
      { letter: 'oo', sound: '/uː/', word: 'food', wordRu: 'еда', emoji: '🍲' },
      { letter: 'oo', sound: '/uː/', word: 'school', wordRu: 'школа', emoji: '🏫' },
    ],
    practiceWords: [
      { word: 'moon', ru: 'луна', emoji: '🌙' },
      { word: 'spoon', ru: 'ложка', emoji: '🥄' },
      { word: 'zoo', ru: 'зоопарк', emoji: '🦁' },
      { word: 'food', ru: 'еда', emoji: '🍕' },
      { word: 'cool', ru: 'прохладный', emoji: '😎' },
      { word: 'pool', ru: 'бассейн', emoji: '🏊' },
      { word: 'room', ru: 'комната', emoji: '🚪' },
      { word: 'school', ru: 'школа', emoji: '🏫' },
      { word: 'too', ru: 'тоже', emoji: '➕' },
      { word: 'roof', ru: 'крыша', emoji: '🏠' },
    ],
  },
  {
    id: 'vt_review',
    title: 'Vowel Teams Review',
    titleRu: 'Повторение сочетаний гласных',
    letters: [
      { letter: 'ee', sound: '/iː/', word: 'tree', wordRu: 'дерево', emoji: '🌳' },
      { letter: 'oa', sound: '/oʊ/', word: 'boat', wordRu: 'лодка', emoji: '⛵' },
    ],
    practiceWords: [
      { word: 'green', ru: 'зелёный', emoji: '💚' },
      { word: 'beach', ru: 'пляж', emoji: '🏖️' },
      { word: 'train', ru: 'поезд', emoji: '🚂' },
      { word: 'boat', ru: 'лодка', emoji: '⛵' },
      { word: 'moon', ru: 'луна', emoji: '🌙' },
      { word: 'sweet', ru: 'сладкий', emoji: '🍬' },
      { word: 'clean', ru: 'чистый', emoji: '✨' },
      { word: 'coat', ru: 'пальто', emoji: '🧥' },
      { word: 'food', ru: 'еда', emoji: '🍕' },
      { word: 'play', ru: 'играть', emoji: '🎮' },
    ],
  },
];
