import type { PhonicsLessonData } from './phonicsLessons';

export const R_CONTROLLED_LESSONS: PhonicsLessonData[] = [
  {
    id: 'rc_ar',
    title: 'R-Controlled AR',
    titleRu: 'AR — /ɑːr/',
    letters: [
      { letter: 'ar', sound: '/ɑːr/', word: 'car', wordRu: 'машина', emoji: '🚗' },
      { letter: 'ar', sound: '/ɑːr/', word: 'star', wordRu: 'звезда', emoji: '⭐' },
      { letter: 'ar', sound: '/ɑːr/', word: 'park', wordRu: 'парк', emoji: '🏞️' },
      { letter: 'ar', sound: '/ɑːr/', word: 'farm', wordRu: 'ферма', emoji: '🌾' },
    ],
    practiceWords: [
      { word: 'car', ru: 'машина', emoji: '🚗' },
      { word: 'star', ru: 'звезда', emoji: '⭐' },
      { word: 'park', ru: 'парк', emoji: '🌳' },
      { word: 'arm', ru: 'рука', emoji: '💪' },
      { word: 'farm', ru: 'ферма', emoji: '🚜' },
      { word: 'dark', ru: 'тёмный', emoji: '🌑' },
      { word: 'card', ru: 'открытка', emoji: '💌' },
      { word: 'jar', ru: 'банка', emoji: '🫙' },
      { word: 'bar', ru: 'полоска', emoji: '🍫' },
      { word: 'hard', ru: 'твёрдый', emoji: '🪨' },
    ],
  },
  {
    id: 'rc_er',
    title: 'R-Controlled ER',
    titleRu: 'ER — /ɜːr/',
    letters: [
      { letter: 'er', sound: '/ɜːr/', word: 'her', wordRu: 'её', emoji: '👩' },
      { letter: 'er', sound: '/ɜːr/', word: 'sister', wordRu: 'сестра', emoji: '👱‍♀️' },
      { letter: 'er', sound: '/ɜːr/', word: 'water', wordRu: 'вода', emoji: '💧' },
      { letter: 'er', sound: '/ɜːr/', word: 'tiger', wordRu: 'тигр', emoji: '🐯' },
    ],
    practiceWords: [
      { word: 'her', ru: 'её', emoji: '👩' },
      { word: 'fern', ru: 'папоротник', emoji: '🌿' },
      { word: 'term', ru: 'срок', emoji: '📋' },
      { word: 'verb', ru: 'глагол', emoji: '📝' },
      { word: 'serve', ru: 'подавать', emoji: '🍽️' },
      { word: 'water', ru: 'вода', emoji: '💧' },
      { word: 'tiger', ru: 'тигр', emoji: '🐯' },
      { word: 'sister', ru: 'сестра', emoji: '👧' },
      { word: 'letter', ru: 'письмо', emoji: '✉️' },
      { word: 'never', ru: 'никогда', emoji: '🚫' },
    ],
  },
  {
    id: 'rc_ir',
    title: 'R-Controlled IR',
    titleRu: 'IR — /ɜːr/',
    letters: [
      { letter: 'ir', sound: '/ɜːr/', word: 'bird', wordRu: 'птица', emoji: '🐦' },
      { letter: 'ir', sound: '/ɜːr/', word: 'girl', wordRu: 'девочка', emoji: '👧' },
      { letter: 'ir', sound: '/ɜːr/', word: 'shirt', wordRu: 'рубашка', emoji: '👕' },
      { letter: 'ir', sound: '/ɜːr/', word: 'first', wordRu: 'первый', emoji: '🥇' },
    ],
    practiceWords: [
      { word: 'bird', ru: 'птица', emoji: '🐦' },
      { word: 'girl', ru: 'девочка', emoji: '👧' },
      { word: 'first', ru: 'первый', emoji: '🥇' },
      { word: 'shirt', ru: 'рубашка', emoji: '👕' },
      { word: 'dirt', ru: 'грязь', emoji: '🟤' },
      { word: 'stir', ru: 'мешать', emoji: '🥄' },
      { word: 'sir', ru: 'сэр', emoji: '🎩' },
      { word: 'third', ru: 'третий', emoji: '🥉' },
      { word: 'skirt', ru: 'юбка', emoji: '👗' },
      { word: 'circle', ru: 'круг', emoji: '⭕' },
    ],
  },
  {
    id: 'rc_or',
    title: 'R-Controlled OR',
    titleRu: 'OR — /ɔːr/',
    letters: [
      { letter: 'or', sound: '/ɔːr/', word: 'horse', wordRu: 'лошадь', emoji: '🐴' },
      { letter: 'or', sound: '/ɔːr/', word: 'door', wordRu: 'дверь', emoji: '🚪' },
      { letter: 'or', sound: '/ɔːr/', word: 'fork', wordRu: 'вилка', emoji: '🍴' },
      { letter: 'or', sound: '/ɔːr/', word: 'sport', wordRu: 'спорт', emoji: '⚽' },
    ],
    practiceWords: [
      { word: 'for', ru: 'для', emoji: '➡️' },
      { word: 'corn', ru: 'кукуруза', emoji: '🌽' },
      { word: 'fork', ru: 'вилка', emoji: '🍴' },
      { word: 'horse', ru: 'лошадь', emoji: '🐴' },
      { word: 'short', ru: 'короткий', emoji: '📏' },
      { word: 'sport', ru: 'спорт', emoji: '⚽' },
      { word: 'born', ru: 'рождённый', emoji: '👶' },
      { word: 'store', ru: 'магазин', emoji: '🏪' },
      { word: 'more', ru: 'больше', emoji: '➕' },
      { word: 'door', ru: 'дверь', emoji: '🚪' },
    ],
  },
  {
    id: 'rc_ur',
    title: 'R-Controlled UR',
    titleRu: 'UR — /ɜːr/',
    letters: [
      { letter: 'ur', sound: '/ɜːr/', word: 'fur', wordRu: 'мех', emoji: '🧸' },
      { letter: 'ur', sound: '/ɜːr/', word: 'nurse', wordRu: 'медсестра', emoji: '👩‍⚕️' },
      { letter: 'ur', sound: '/ɜːr/', word: 'purple', wordRu: 'фиолетовый', emoji: '🟣' },
      { letter: 'ur', sound: '/ɜːr/', word: 'turn', wordRu: 'поворот', emoji: '↩️' },
    ],
    practiceWords: [
      { word: 'fur', ru: 'мех', emoji: '🧸' },
      { word: 'turn', ru: 'поворот', emoji: '🔄' },
      { word: 'burn', ru: 'гореть', emoji: '🔥' },
      { word: 'hurt', ru: 'больно', emoji: '🤕' },
      { word: 'nurse', ru: 'медсестра', emoji: '👩‍⚕️' },
      { word: 'purple', ru: 'фиолетовый', emoji: '💜' },
      { word: 'church', ru: 'церковь', emoji: '⛪' },
      { word: 'surf', ru: 'сёрфинг', emoji: '🏄' },
      { word: 'curl', ru: 'завиток', emoji: '🌀' },
      { word: 'burst', ru: 'взрыв', emoji: '💥' },
    ],
  },
];
