import type { PhonicsLessonData } from './phonicsLessons';

export const LONG_VOWEL_LESSONS: PhonicsLessonData[] = [
  {
    id: 'long_a_e',
    title: 'Magic E — Long A',
    titleRu: 'Волшебная E — долгое A /eɪ/',
    letters: [
      { letter: 'a_e', sound: '/eɪ/', word: 'cake', wordRu: 'торт', emoji: '🎂' },
      { letter: 'a_e', sound: '/eɪ/', word: 'name', wordRu: 'имя', emoji: '📛' },
      { letter: 'a_e', sound: '/eɪ/', word: 'game', wordRu: 'игра', emoji: '🎮' },
      { letter: 'a_e', sound: '/eɪ/', word: 'lake', wordRu: 'озеро', emoji: '🏞️' },
    ],
    practiceWords: [
      { word: 'cake', ru: 'торт', emoji: '🎂' },
      { word: 'lake', ru: 'озеро', emoji: '🏞️' },
      { word: 'make', ru: 'делать', emoji: '🛠️' },
      { word: 'name', ru: 'имя', emoji: '📛' },
      { word: 'game', ru: 'игра', emoji: '🎮' },
      { word: 'gate', ru: 'ворота', emoji: '🚪' },
      { word: 'late', ru: 'поздно', emoji: '⏰' },
      { word: 'wave', ru: 'волна', emoji: '🌊' },
      { word: 'save', ru: 'спасать', emoji: '💾' },
      { word: 'plate', ru: 'тарелка', emoji: '🍽️' },
    ],
  },
  {
    id: 'long_i_e',
    title: 'Magic E — Long I',
    titleRu: 'Волшебная E — долгое I /aɪ/',
    letters: [
      { letter: 'i_e', sound: '/aɪ/', word: 'bike', wordRu: 'велосипед', emoji: '🚲' },
      { letter: 'i_e', sound: '/aɪ/', word: 'like', wordRu: 'нравиться', emoji: '👍' },
      { letter: 'i_e', sound: '/aɪ/', word: 'five', wordRu: 'пять', emoji: '5️⃣' },
      { letter: 'i_e', sound: '/aɪ/', word: 'kite', wordRu: 'воздушный змей', emoji: '🪁' },
    ],
    practiceWords: [
      { word: 'bike', ru: 'велосипед', emoji: '🚲' },
      { word: 'like', ru: 'нравиться', emoji: '👍' },
      { word: 'time', ru: 'время', emoji: '⏰' },
      { word: 'nine', ru: 'девять', emoji: '9️⃣' },
      { word: 'five', ru: 'пять', emoji: '5️⃣' },
      { word: 'kite', ru: 'воздушный змей', emoji: '🪁' },
      { word: 'ride', ru: 'кататься', emoji: '🏇' },
      { word: 'hide', ru: 'прятаться', emoji: '🙈' },
      { word: 'line', ru: 'линия', emoji: '📏' },
      { word: 'fine', ru: 'отлично', emoji: '👌' },
    ],
  },
  {
    id: 'long_o_e',
    title: 'Magic E — Long O',
    titleRu: 'Волшебная E — долгое O /oʊ/',
    letters: [
      { letter: 'o_e', sound: '/oʊ/', word: 'home', wordRu: 'дом', emoji: '🏠' },
      { letter: 'o_e', sound: '/oʊ/', word: 'nose', wordRu: 'нос', emoji: '👃' },
      { letter: 'o_e', sound: '/oʊ/', word: 'rose', wordRu: 'роза', emoji: '🌹' },
      { letter: 'o_e', sound: '/oʊ/', word: 'bone', wordRu: 'кость', emoji: '🦴' },
    ],
    practiceWords: [
      { word: 'home', ru: 'дом', emoji: '🏠' },
      { word: 'nose', ru: 'нос', emoji: '👃' },
      { word: 'bone', ru: 'кость', emoji: '🦴' },
      { word: 'note', ru: 'записка', emoji: '📝' },
      { word: 'rose', ru: 'роза', emoji: '🌹' },
      { word: 'hope', ru: 'надежда', emoji: '🤞' },
      { word: 'rope', ru: 'верёвка', emoji: '🪢' },
      { word: 'stone', ru: 'камень', emoji: '🪨' },
      { word: 'phone', ru: 'телефон', emoji: '📱' },
      { word: 'hole', ru: 'дыра', emoji: '🕳️' },
    ],
  },
  {
    id: 'long_u_e',
    title: 'Magic E — Long U',
    titleRu: 'Волшебная E — долгое U /juː/',
    letters: [
      { letter: 'u_e', sound: '/juː/', word: 'cute', wordRu: 'милый', emoji: '🥰' },
      { letter: 'u_e', sound: '/juː/', word: 'cube', wordRu: 'куб', emoji: '🧊' },
      { letter: 'u_e', sound: '/juː/', word: 'huge', wordRu: 'огромный', emoji: '🐋' },
      { letter: 'u_e', sound: '/juː/', word: 'flute', wordRu: 'флейта', emoji: '🪈' },
    ],
    practiceWords: [
      { word: 'cute', ru: 'милый', emoji: '🥰' },
      { word: 'huge', ru: 'огромный', emoji: '🐋' },
      { word: 'tube', ru: 'труба', emoji: '🧪' },
      { word: 'cube', ru: 'куб', emoji: '🧊' },
      { word: 'mule', ru: 'мул', emoji: '🫏' },
      { word: 'June', ru: 'июнь', emoji: '☀️' },
      { word: 'rule', ru: 'правило', emoji: '📐' },
      { word: 'flute', ru: 'флейта', emoji: '🪈' },
      { word: 'fuse', ru: 'предохранитель', emoji: '🔌' },
      { word: 'use', ru: 'использовать', emoji: '✋' },
    ],
  },
  {
    id: 'long_e_e',
    title: 'Magic E — Long E',
    titleRu: 'Волшебная E — долгое E /iː/',
    letters: [
      { letter: 'e_e', sound: '/iː/', word: 'Pete', wordRu: 'Пит (имя)', emoji: '👦' },
      { letter: 'e_e', sound: '/iː/', word: 'these', wordRu: 'эти', emoji: '👉' },
      { letter: 'e_e', sound: '/iː/', word: 'theme', wordRu: 'тема', emoji: '📚' },
    ],
    practiceWords: [
      { word: 'Pete', ru: 'Пит (имя)', emoji: '👦' },
      { word: 'these', ru: 'эти', emoji: '👉' },
      { word: 'theme', ru: 'тема', emoji: '📚' },
      { word: 'Eve', ru: 'Ева (имя)', emoji: '👧' },
      { word: 'Steve', ru: 'Стив (имя)', emoji: '🧑' },
    ],
  },
];
