import type { PhonicsLessonData } from './phonicsLessons';

export const SIGHT_WORD_LESSONS: PhonicsLessonData[] = [
  {
    id: 'sight_1',
    title: 'Sight Words 1',
    titleRu: 'Слова для запоминания — группа 1',
    letters: [{ letter: '👁️', sound: '', word: 'sight words', wordRu: 'слова для запоминания', emoji: '👁️' }],
    practiceWords: [
      { word: 'the', ru: 'этот/эта/это', emoji: '👉' },
      { word: 'a', ru: 'один/одна', emoji: '1️⃣' },
      { word: 'is', ru: 'есть/является', emoji: '✅' },
      { word: 'it', ru: 'это/оно', emoji: '👆' },
      { word: 'in', ru: 'в', emoji: '📥' },
      { word: 'I', ru: 'я', emoji: '🙋' },
      { word: 'to', ru: 'к/до', emoji: '➡️' },
      { word: 'and', ru: 'и', emoji: '🤝' },
      { word: 'we', ru: 'мы', emoji: '👫' },
      { word: 'he', ru: 'он', emoji: '👦' },
    ],
  },
  {
    id: 'sight_2',
    title: 'Sight Words 2',
    titleRu: 'Слова для запоминания — группа 2',
    letters: [{ letter: '👁️', sound: '', word: 'sight words', wordRu: 'слова для запоминания', emoji: '👁️' }],
    practiceWords: [
      { word: 'she', ru: 'она', emoji: '👧' },
      { word: 'my', ru: 'мой', emoji: '💎' },
      { word: 'you', ru: 'ты/вы', emoji: '🫵' },
      { word: 'are', ru: 'есть (мн.)', emoji: '✔️' },
      { word: 'was', ru: 'был/была', emoji: '⏪' },
      { word: 'they', ru: 'они', emoji: '👥' },
      { word: 'on', ru: 'на', emoji: '🔛' },
      { word: 'can', ru: 'могу', emoji: '💪' },
      { word: 'has', ru: 'имеет', emoji: '🎁' },
      { word: 'his', ru: 'его', emoji: '👦' },
    ],
  },
  {
    id: 'sight_3',
    title: 'Sight Words 3',
    titleRu: 'Слова для запоминания — группа 3',
    letters: [{ letter: '👁️', sound: '', word: 'sight words', wordRu: 'слова для запоминания', emoji: '👁️' }],
    practiceWords: [
      { word: 'her', ru: 'её', emoji: '👩' },
      { word: 'all', ru: 'все/всё', emoji: '🌍' },
      { word: 'said', ru: 'сказал', emoji: '💬' },
      { word: 'do', ru: 'делать', emoji: '🛠️' },
      { word: 'like', ru: 'нравится', emoji: '❤️' },
      { word: 'have', ru: 'иметь', emoji: '🤲' },
      { word: 'this', ru: 'этот', emoji: '👇' },
      { word: 'will', ru: 'буду', emoji: '🔮' },
      { word: 'with', ru: 'с', emoji: '🤝' },
      { word: 'one', ru: 'один', emoji: '☝️' },
    ],
  },
  {
    id: 'sight_4',
    title: 'Sight Words 4',
    titleRu: 'Слова для запоминания — группа 4',
    letters: [{ letter: '👁️', sound: '', word: 'sight words', wordRu: 'слова для запоминания', emoji: '👁️' }],
    practiceWords: [
      { word: 'no', ru: 'нет', emoji: '🚫' },
      { word: 'go', ru: 'идти', emoji: '🚶' },
      { word: 'so', ru: 'так', emoji: '💡' },
      { word: 'not', ru: 'не', emoji: '❌' },
      { word: 'but', ru: 'но', emoji: '↩️' },
      { word: 'what', ru: 'что', emoji: '❓' },
      { word: 'there', ru: 'там', emoji: '📍' },
      { word: 'out', ru: 'наружу', emoji: '📤' },
      { word: 'be', ru: 'быть', emoji: '🌟' },
      { word: 'up', ru: 'вверх', emoji: '⬆️' },
    ],
  },
  {
    id: 'sight_5',
    title: 'Sight Words 5',
    titleRu: 'Слова для запоминания — группа 5',
    letters: [{ letter: '👁️', sound: '', word: 'sight words', wordRu: 'слова для запоминания', emoji: '👁️' }],
    practiceWords: [
      { word: 'look', ru: 'смотреть', emoji: '👀' },
      { word: 'some', ru: 'немного', emoji: '🤏' },
      { word: 'come', ru: 'приходить', emoji: '🏃' },
      { word: 'very', ru: 'очень', emoji: '💯' },
      { word: 'here', ru: 'здесь', emoji: '📌' },
      { word: 'just', ru: 'просто', emoji: '👌' },
      { word: 'were', ru: 'были', emoji: '⏪' },
      { word: 'your', ru: 'твой/ваш', emoji: '🫵' },
      { word: 'when', ru: 'когда', emoji: '⏰' },
      { word: 'had', ru: 'имел', emoji: '📦' },
    ],
  },
];
