// Russian explanations for phonics rules and grammar
// Each has a text explanation + examples + tip

export interface PhonicsExplanation {
  id: string;
  rule: string;          // e.g. "th", "sh", "short_a"
  titleEn: string;
  titleRu: string;
  explanation: string;   // Russian explanation (read by TTS)
  tip: string;           // Mnemonic / physical tip
  examples: { word: string; transcription: string; ru: string; note?: string }[];
  practiceWords: string[];
}

export interface GrammarExplanation {
  id: string;
  topic: string;
  titleEn: string;
  titleRu: string;
  level: string;         // "2-3", "3-4", "5-6", "7-8"
  explanation: string;
  ruAnalogy: string;     // "В русском это как..."
  formula: string;       // "am/is/are + verb-ing"
  examples: { en: string; ru: string; highlight: string }[];
  antiExamples?: { wrong: string; right: string; whyRu: string }[];
  tip: string;
}

export const PHONICS_EXPLANATIONS: PhonicsExplanation[] = [
  {
    id: 'ph_th',
    rule: 'th',
    titleEn: 'TH sound',
    titleRu: 'Звук TH',
    explanation: 'Буквосочетание TH читается как мягкое «з» или «с», но язык нужно поставить между зубами. Это самый необычный звук для русского уха! Попробуй сказать «з», но прикуси кончик языка — получится th! Есть два варианта: звонкий — как в слове this, и глухой — как в слове three.',
    tip: 'Положи кончик языка между зубами и подуй. Если добавишь голос — получится звонкий th (this). Без голоса — глухой th (three).',
    examples: [
      { word: 'this', transcription: '/ðɪs/', ru: 'это', note: 'звонкий th — язык между зубами + голос' },
      { word: 'that', transcription: '/ðæt/', ru: 'тот', note: 'звонкий th' },
      { word: 'the', transcription: '/ðə/', ru: 'определённый артикль', note: 'звонкий th' },
      { word: 'three', transcription: '/θriː/', ru: 'три', note: 'глухой th — язык между зубами, без голоса' },
      { word: 'thin', transcription: '/θɪn/', ru: 'тонкий', note: 'глухой th' },
      { word: 'thick', transcription: '/θɪk/', ru: 'толстый', note: 'глухой th' },
    ],
    practiceWords: ['this', 'that', 'the', 'them', 'three', 'thin', 'thick', 'bath', 'math', 'with'],
  },
  {
    id: 'ph_sh',
    rule: 'sh',
    titleEn: 'SH sound',
    titleRu: 'Звук SH',
    explanation: 'Буквосочетание SH читается как русское «ш», но мягче. Представь что ты просишь кого-то быть тише: «Шшш!». Вот это и есть английский звук sh.',
    tip: 'Скажи русское «ш» и улыбнись — звук станет мягче. Это и будет английское sh!',
    examples: [
      { word: 'ship', transcription: '/ʃɪp/', ru: 'корабль' },
      { word: 'shop', transcription: '/ʃɒp/', ru: 'магазин' },
      { word: 'fish', transcription: '/fɪʃ/', ru: 'рыба' },
      { word: 'she', transcription: '/ʃiː/', ru: 'она' },
      { word: 'shoe', transcription: '/ʃuː/', ru: 'ботинок' },
      { word: 'sheep', transcription: '/ʃiːp/', ru: 'овца' },
    ],
    practiceWords: ['ship', 'shop', 'fish', 'dish', 'she', 'shoe', 'shell', 'shut', 'wish', 'push'],
  },
  {
    id: 'ph_ch',
    rule: 'ch',
    titleEn: 'CH sound',
    titleRu: 'Звук CH',
    explanation: 'Буквосочетание CH читается как русское «ч». Это один из самых простых звуков для русских — у нас точно такой же! Просто говори «ч» как обычно.',
    tip: 'CH = русское «ч». Легко!',
    examples: [
      { word: 'chip', transcription: '/tʃɪp/', ru: 'чипсина' },
      { word: 'chat', transcription: '/tʃæt/', ru: 'болтать' },
      { word: 'much', transcription: '/mʌtʃ/', ru: 'много' },
      { word: 'lunch', transcription: '/lʌntʃ/', ru: 'обед' },
      { word: 'cheese', transcription: '/tʃiːz/', ru: 'сыр' },
      { word: 'chicken', transcription: '/ˈtʃɪkɪn/', ru: 'курица' },
    ],
    practiceWords: ['chip', 'chat', 'chin', 'chop', 'much', 'such', 'rich', 'check', 'chest', 'lunch'],
  },
  {
    id: 'ph_short_a',
    rule: 'short_a',
    titleEn: 'Short A',
    titleRu: 'Короткое A',
    explanation: 'Короткое A читается как звук между русскими «э» и «а». Откройте рот широко, как будто доктор просит сказать «а-а-а», но более коротко и резко. Этот звук встречается в коротких словах вроде cat, hat, man.',
    tip: 'Откройте рот как для «а», но скажите «э». Получится короткое английское a. Как в слове «кэт» — cat.',
    examples: [
      { word: 'cat', transcription: '/kæt/', ru: 'кот' },
      { word: 'hat', transcription: '/hæt/', ru: 'шляпа' },
      { word: 'man', transcription: '/mæn/', ru: 'мужчина' },
      { word: 'bag', transcription: '/bæɡ/', ru: 'сумка' },
      { word: 'map', transcription: '/mæp/', ru: 'карта' },
      { word: 'sad', transcription: '/sæd/', ru: 'грустный' },
    ],
    practiceWords: ['cat', 'hat', 'bat', 'man', 'can', 'van', 'map', 'bag', 'sad', 'dad'],
  },
  {
    id: 'ph_magic_e',
    rule: 'magic_e',
    titleEn: 'Magic E',
    titleRu: 'Волшебная E',
    explanation: 'Волшебная E — это немая буква e в конце слова, которая делает гласную перед ней длинной! Сама E не произносится, но меняет звук. Сравни: can — cane. В can буква a короткая. Добавили e в конец — и a стала длинной, как в алфавите! Вот такое волшебство.',
    tip: 'Буква E в конце слова — как волшебная палочка. Она сама молчит, но делает гласную длинной. cap → cape, not → note, cut → cute.',
    examples: [
      { word: 'cake', transcription: '/keɪk/', ru: 'торт', note: 'a читается как «эй»' },
      { word: 'bike', transcription: '/baɪk/', ru: 'велосипед', note: 'i читается как «ай»' },
      { word: 'home', transcription: '/hoʊm/', ru: 'дом', note: 'o читается как «оу»' },
      { word: 'cute', transcription: '/kjuːt/', ru: 'милый', note: 'u читается как «ю»' },
      { word: 'name', transcription: '/neɪm/', ru: 'имя', note: 'a читается как «эй»' },
      { word: 'like', transcription: '/laɪk/', ru: 'нравиться', note: 'i читается как «ай»' },
    ],
    practiceWords: ['cake', 'make', 'lake', 'bike', 'like', 'time', 'home', 'nose', 'cute', 'name'],
  },
  {
    id: 'ph_short_e',
    rule: 'short_e',
    titleEn: 'Short E',
    titleRu: 'Короткое E',
    explanation: 'Короткое E звучит как русское «э» в слове «это». Рот чуть приоткрыт, язык внизу. Этот звук встречается в коротких словах: bed, pen, red.',
    tip: 'Скажи русское «э» коротко и отрывисто — вот тебе английское short E!',
    examples: [
      { word: 'bed', transcription: '/bɛd/', ru: 'кровать' },
      { word: 'pen', transcription: '/pɛn/', ru: 'ручка' },
      { word: 'red', transcription: '/rɛd/', ru: 'красный' },
      { word: 'ten', transcription: '/tɛn/', ru: 'десять' },
      { word: 'hen', transcription: '/hɛn/', ru: 'курица' },
      { word: 'leg', transcription: '/lɛɡ/', ru: 'нога' },
    ],
    practiceWords: ['bed', 'pen', 'red', 'ten', 'hen', 'leg', 'men', 'net', 'pet', 'wet'],
  },
  {
    id: 'ph_short_i',
    rule: 'short_i',
    titleEn: 'Short I',
    titleRu: 'Короткое I',
    explanation: 'Короткое I — это звук между русскими «и» и «ы». Он короче и расслабленнее, чем русское «и». Встречается в словах: big, sit, fish.',
    tip: 'Скажи «и», но не напрягай губы и не улыбайся — получится расслабленный звук, как в слове «бИг».',
    examples: [
      { word: 'big', transcription: '/bɪɡ/', ru: 'большой' },
      { word: 'sit', transcription: '/sɪt/', ru: 'сидеть' },
      { word: 'fish', transcription: '/fɪʃ/', ru: 'рыба' },
      { word: 'pig', transcription: '/pɪɡ/', ru: 'свинья' },
      { word: 'milk', transcription: '/mɪlk/', ru: 'молоко' },
      { word: 'six', transcription: '/sɪks/', ru: 'шесть' },
    ],
    practiceWords: ['big', 'sit', 'fish', 'pig', 'milk', 'six', 'kid', 'hit', 'win', 'pin'],
  },
  {
    id: 'ph_short_o',
    rule: 'short_o',
    titleEn: 'Short O',
    titleRu: 'Короткое O',
    explanation: 'Короткое O звучит как русское «о» в слове «бот», но рот открыт шире. Представь, что доктор просит открыть рот — вот так и произносится short O.',
    tip: 'Открой рот широко, как у доктора, и скажи «о» — получится английское short O. Как в слове «дог» — dog.',
    examples: [
      { word: 'dog', transcription: '/dɒɡ/', ru: 'собака' },
      { word: 'hot', transcription: '/hɒt/', ru: 'горячий' },
      { word: 'box', transcription: '/bɒks/', ru: 'коробка' },
      { word: 'fox', transcription: '/fɒks/', ru: 'лиса' },
      { word: 'top', transcription: '/tɒp/', ru: 'верх' },
      { word: 'frog', transcription: '/frɒɡ/', ru: 'лягушка' },
    ],
    practiceWords: ['dog', 'hot', 'box', 'fox', 'top', 'frog', 'pot', 'lot', 'not', 'got'],
  },
  {
    id: 'ph_short_u',
    rule: 'short_u',
    titleEn: 'Short U',
    titleRu: 'Короткое U',
    explanation: 'Короткое U звучит как русское «а» в слове «масло», но короче. Рот почти не открывается, звук идёт из середины рта. Встречается в словах: bus, cup, sun.',
    tip: 'Скажи короткое «а», почти не открывая рот — вот тебе английское short U! Как в слове «бас» — bus.',
    examples: [
      { word: 'bus', transcription: '/bʌs/', ru: 'автобус' },
      { word: 'cup', transcription: '/kʌp/', ru: 'чашка' },
      { word: 'sun', transcription: '/sʌn/', ru: 'солнце' },
      { word: 'run', transcription: '/rʌn/', ru: 'бегать' },
      { word: 'fun', transcription: '/fʌn/', ru: 'веселье' },
      { word: 'mum', transcription: '/mʌm/', ru: 'мама' },
    ],
    practiceWords: ['bus', 'cup', 'sun', 'run', 'fun', 'mum', 'but', 'cut', 'hug', 'nut'],
  },
  {
    id: 'ph_consonant_blends',
    rule: 'consonant_blends',
    titleEn: 'Consonant Blends',
    titleRu: 'Сочетания согласных',
    explanation: 'Consonant blends — это когда две или три согласные стоят рядом и каждая произносится! В отличие от русского, где «вс» в слове «всё» звучит слитно, в английском каждый звук слышен отдельно: bl, br, cl, cr, dr, fl, fr, gl, gr, pl, pr, sl, sm, sn, sp, st, sw, tr.',
    tip: 'В blend каждая буква звучит! BR — сначала «б», потом сразу «р». Не «бэр», а «бр»! Потренируйся: br-ead, cl-ap, gr-een.',
    examples: [
      { word: 'black', transcription: '/blæk/', ru: 'чёрный', note: 'bl — б+л' },
      { word: 'green', transcription: '/ɡriːn/', ru: 'зелёный', note: 'gr — г+р' },
      { word: 'tree', transcription: '/triː/', ru: 'дерево', note: 'tr — т+р' },
      { word: 'stop', transcription: '/stɒp/', ru: 'стоп', note: 'st — с+т' },
      { word: 'flower', transcription: '/ˈflaʊər/', ru: 'цветок', note: 'fl — ф+л' },
      { word: 'swim', transcription: '/swɪm/', ru: 'плавать', note: 'sw — с+в' },
    ],
    practiceWords: ['black', 'brown', 'clap', 'cream', 'drink', 'flag', 'frog', 'green', 'play', 'tree'],
  },
  {
    id: 'ph_long_vowels',
    rule: 'long_vowels',
    titleEn: 'Long Vowels',
    titleRu: 'Долгие гласные',
    explanation: 'Долгие гласные — это когда буква читается как в алфавите. A = «эй», E = «ии», I = «ай», O = «оу», U = «ю». Обычно долгая гласная получается, когда в конце слова стоит немая E (magic E): cake, like, home. Или когда две гласные стоят рядом: rain, sea, boat.',
    tip: 'Долгая гласная = буква звучит как в алфавите. Запомни: «When two vowels go walking, the first one does the talking» — когда две гласные рядом, первая говорит своё имя!',
    examples: [
      { word: 'cake', transcription: '/keɪk/', ru: 'торт', note: 'long A = «эй»' },
      { word: 'tree', transcription: '/triː/', ru: 'дерево', note: 'long E = «ии»' },
      { word: 'bike', transcription: '/baɪk/', ru: 'велосипед', note: 'long I = «ай»' },
      { word: 'home', transcription: '/hoʊm/', ru: 'дом', note: 'long O = «оу»' },
      { word: 'cute', transcription: '/kjuːt/', ru: 'милый', note: 'long U = «ю»' },
    ],
    practiceWords: ['cake', 'name', 'tree', 'see', 'bike', 'five', 'home', 'nose', 'cute', 'tube'],
  },
  {
    id: 'ph_wh',
    rule: 'wh',
    titleEn: 'WH sound',
    titleRu: 'Звук WH',
    explanation: 'Буквосочетание WH в начале слова обычно читается как «в» (русское «в» с округлёнными губами). Буква H не произносится! what = «вот», when = «вэн», where = «вэа». Исключение: who, whose, whom — там наоборот, W не читается, а читается только H.',
    tip: 'WH = «в» (губы трубочкой). Но в словах who, whose — читается как «х».',
    examples: [
      { word: 'what', transcription: '/wɒt/', ru: 'что' },
      { word: 'when', transcription: '/wɛn/', ru: 'когда' },
      { word: 'where', transcription: '/wɛər/', ru: 'где' },
      { word: 'white', transcription: '/waɪt/', ru: 'белый' },
      { word: 'why', transcription: '/waɪ/', ru: 'почему' },
      { word: 'who', transcription: '/huː/', ru: 'кто', note: 'исключение! Читается «ху»' },
    ],
    practiceWords: ['what', 'when', 'where', 'white', 'why', 'which', 'while', 'wheel', 'whale', 'whistle'],
  },
  {
    id: 'ph_ph',
    rule: 'ph',
    titleEn: 'PH sound',
    titleRu: 'Звук PH',
    explanation: 'Буквосочетание PH читается как «ф»! Это пришло из греческого языка. Слова с PH часто «умные»: phone, photo, elephant. Легко запомнить: PH = F.',
    tip: 'PH = Ф. Всё просто! phone = фон, photo = фото.',
    examples: [
      { word: 'phone', transcription: '/foʊn/', ru: 'телефон' },
      { word: 'photo', transcription: '/ˈfoʊtoʊ/', ru: 'фото' },
      { word: 'elephant', transcription: '/ˈɛlɪfənt/', ru: 'слон' },
      { word: 'dolphin', transcription: '/ˈdɒlfɪn/', ru: 'дельфин' },
      { word: 'alphabet', transcription: '/ˈælfəbɛt/', ru: 'алфавит' },
    ],
    practiceWords: ['phone', 'photo', 'elephant', 'dolphin', 'alphabet', 'graph', 'phrase', 'pharmacy'],
  },
  {
    id: 'ph_ck',
    rule: 'ck',
    titleEn: 'CK sound',
    titleRu: 'Звук CK',
    explanation: 'Буквосочетание CK читается как «к». Оно ставится после короткой гласной: back, duck, sock. Запомни: если гласная короткая, пишем CK. Если длинная — просто K (like, bike).',
    tip: 'CK = К после короткой гласной. Duck, sock, black — всё с коротким звуком перед CK.',
    examples: [
      { word: 'duck', transcription: '/dʌk/', ru: 'утка' },
      { word: 'black', transcription: '/blæk/', ru: 'чёрный' },
      { word: 'sock', transcription: '/sɒk/', ru: 'носок' },
      { word: 'clock', transcription: '/klɒk/', ru: 'часы' },
      { word: 'chicken', transcription: '/ˈtʃɪkɪn/', ru: 'курица' },
      { word: 'kick', transcription: '/kɪk/', ru: 'пинать' },
    ],
    practiceWords: ['duck', 'black', 'sock', 'clock', 'kick', 'back', 'neck', 'stick', 'truck', 'rock'],
  },
  {
    id: 'ph_ng',
    rule: 'ng',
    titleEn: 'NG sound',
    titleRu: 'Звук NG',
    explanation: 'Буквосочетание NG читается как носовой звук «нг» — воздух идёт через нос! Это не «н» + «г», а один особый звук. Кончик языка не касается нёба, а задняя часть языка поднимается. Слова: sing, ring, long.',
    tip: 'Скажи «н», но не трогай языком нёбо, а подними заднюю часть языка — получится носовое «нг». Как в слове «сИНГ» — sing.',
    examples: [
      { word: 'sing', transcription: '/sɪŋ/', ru: 'петь' },
      { word: 'ring', transcription: '/rɪŋ/', ru: 'кольцо' },
      { word: 'long', transcription: '/lɒŋ/', ru: 'длинный' },
      { word: 'song', transcription: '/sɒŋ/', ru: 'песня' },
      { word: 'king', transcription: '/kɪŋ/', ru: 'король' },
      { word: 'morning', transcription: '/ˈmɔːrnɪŋ/', ru: 'утро' },
    ],
    practiceWords: ['sing', 'ring', 'long', 'song', 'king', 'morning', 'evening', 'spring', 'swing', 'strong'],
  },
  {
    id: 'ph_ee_ea',
    rule: 'ee_ea',
    titleEn: 'EE & EA sounds',
    titleRu: 'Звуки EE и EA',
    explanation: 'EE и EA обычно читаются одинаково — как долгое «ии»! Tree, see, green — это EE. Tea, sea, read — это EA. Обе пары дают звук /iː/. Исключения: bread, head — тут EA читается как короткое «э».',
    tip: 'EE = «ии» всегда! EA = «ии» почти всегда. Исключения: bread, head, breakfast — там EA = «э».',
    examples: [
      { word: 'tree', transcription: '/triː/', ru: 'дерево', note: 'EE = «ии»' },
      { word: 'see', transcription: '/siː/', ru: 'видеть', note: 'EE = «ии»' },
      { word: 'tea', transcription: '/tiː/', ru: 'чай', note: 'EA = «ии»' },
      { word: 'sea', transcription: '/siː/', ru: 'море', note: 'EA = «ии»' },
      { word: 'bread', transcription: '/brɛd/', ru: 'хлеб', note: 'EA = «э» (исключение!)' },
      { word: 'head', transcription: '/hɛd/', ru: 'голова', note: 'EA = «э» (исключение!)' },
    ],
    practiceWords: ['tree', 'see', 'green', 'feet', 'tea', 'sea', 'eat', 'read', 'meat', 'clean'],
  },
  {
    id: 'ph_ai_ay',
    rule: 'ai_ay',
    titleEn: 'AI & AY sounds',
    titleRu: 'Звуки AI и AY',
    explanation: 'AI и AY читаются как долгое «эй» — как буква A в алфавите! AI стоит внутри слова: rain, train, paint. AY стоит в конце слова: play, day, say. Правило простое: в середине — AI, в конце — AY.',
    tip: 'AI = «эй» в середине слова, AY = «эй» в конце. Rain — play, train — day.',
    examples: [
      { word: 'rain', transcription: '/reɪn/', ru: 'дождь', note: 'AI в середине' },
      { word: 'train', transcription: '/treɪn/', ru: 'поезд', note: 'AI в середине' },
      { word: 'play', transcription: '/pleɪ/', ru: 'играть', note: 'AY в конце' },
      { word: 'day', transcription: '/deɪ/', ru: 'день', note: 'AY в конце' },
      { word: 'say', transcription: '/seɪ/', ru: 'говорить', note: 'AY в конце' },
    ],
    practiceWords: ['rain', 'train', 'paint', 'wait', 'play', 'day', 'say', 'stay', 'today', 'birthday'],
  },
  {
    id: 'ph_oa_oo',
    rule: 'oa_oo',
    titleEn: 'OA & OO sounds',
    titleRu: 'Звуки OA и OO',
    explanation: 'OA читается как долгое «оу» — как буква O в алфавите: boat, coat, road. OO имеет два звука: долгое «уу» (moon, food, school) и короткое «у» (book, cook, look). Большинство слов с OO = «уу».',
    tip: 'OA = «оу» (boat, coat). OO = обычно «уу» (moon, school), но в book, cook, look — короткое «у».',
    examples: [
      { word: 'boat', transcription: '/boʊt/', ru: 'лодка', note: 'OA = «оу»' },
      { word: 'coat', transcription: '/koʊt/', ru: 'пальто', note: 'OA = «оу»' },
      { word: 'moon', transcription: '/muːn/', ru: 'луна', note: 'OO = долгое «уу»' },
      { word: 'school', transcription: '/skuːl/', ru: 'школа', note: 'OO = долгое «уу»' },
      { word: 'book', transcription: '/bʊk/', ru: 'книга', note: 'OO = короткое «у»' },
      { word: 'cook', transcription: '/kʊk/', ru: 'готовить', note: 'OO = короткое «у»' },
    ],
    practiceWords: ['boat', 'coat', 'road', 'moon', 'food', 'school', 'too', 'book', 'cook', 'look'],
  },
  {
    id: 'ph_r_controlled',
    rule: 'r_controlled',
    titleEn: 'R-controlled vowels',
    titleRu: 'Гласные перед R',
    explanation: 'Когда после гласной стоит R, она меняет свой звук! AR = «ар» (car, star). OR = «ор» (fork, horse). ER, IR, UR — все три звучат одинаково, как «ёр»: her, bird, turn. R «управляет» гласной — поэтому они называются R-controlled.',
    tip: 'AR = «ар», OR = «ор», а ER/IR/UR все три = «ёр». Bird, her, turn — один звук!',
    examples: [
      { word: 'car', transcription: '/kɑːr/', ru: 'машина', note: 'AR = «ар»' },
      { word: 'star', transcription: '/stɑːr/', ru: 'звезда', note: 'AR = «ар»' },
      { word: 'horse', transcription: '/hɔːrs/', ru: 'лошадь', note: 'OR = «ор»' },
      { word: 'bird', transcription: '/bɜːrd/', ru: 'птица', note: 'IR = «ёр»' },
      { word: 'her', transcription: '/hɜːr/', ru: 'её', note: 'ER = «ёр»' },
      { word: 'turn', transcription: '/tɜːrn/', ru: 'поворот', note: 'UR = «ёр»' },
    ],
    practiceWords: ['car', 'star', 'farm', 'horse', 'fork', 'bird', 'girl', 'her', 'turn', 'nurse'],
  },
  {
    id: 'ph_sight_words',
    rule: 'sight_words',
    titleEn: 'Sight Words',
    titleRu: 'Слова для запоминания',
    explanation: 'Sight words — это частые слова, которые не читаются по правилам. Их нужно просто запомнить! Например: the, said, was, come, some, one, two, do, you. Эти слова встречаются в каждом тексте, поэтому важно знать их «в лицо».',
    tip: 'Sight words нужно запоминать целиком, как картинку. Читай их почаще — и они запомнятся сами!',
    examples: [
      { word: 'the', transcription: '/ðə/', ru: 'артикль', note: 'не читается по правилам' },
      { word: 'said', transcription: '/sɛd/', ru: 'сказал', note: 'AI здесь = «э», не «эй»!' },
      { word: 'come', transcription: '/kʌm/', ru: 'приходить', note: 'O = «а», не «о»' },
      { word: 'some', transcription: '/sʌm/', ru: 'некоторые', note: 'O = «а»' },
      { word: 'one', transcription: '/wʌn/', ru: 'один', note: 'читается «ван»!' },
      { word: 'two', transcription: '/tuː/', ru: 'два', note: 'W не читается!' },
    ],
    practiceWords: ['the', 'said', 'come', 'some', 'one', 'two', 'do', 'you', 'was', 'are'],
  },
];

export const GRAMMAR_EXPLANATIONS: GrammarExplanation[] = [
  {
    id: 'gr_to_be',
    topic: 'to_be',
    titleEn: 'To Be — am, is, are',
    titleRu: 'Глагол «быть» — am, is, are',
    level: '2-3',
    explanation: 'В русском мы говорим «Я ученик», «Она красивая» — без глагола. А в английском обязательно нужен глагол «быть»: I am a student, She is beautiful. Нельзя сказать просто «I student» — англичане не поймут!',
    ruAnalogy: 'В русском глагол «есть» обычно пропускается: «Я — ученик». В английском его пропускать нельзя: I AM a student.',
    formula: 'I → am  |  He/She/It → is  |  We/You/They → are',
    examples: [
      { en: 'I am happy.', ru: 'Я счастливый.', highlight: 'am' },
      { en: 'She is a teacher.', ru: 'Она учительница.', highlight: 'is' },
      { en: 'They are friends.', ru: 'Они друзья.', highlight: 'are' },
      { en: 'It is cold.', ru: 'Холодно.', highlight: 'is' },
      { en: 'We are at school.', ru: 'Мы в школе.', highlight: 'are' },
    ],
    antiExamples: [
      { wrong: 'I happy.', right: 'I am happy.', whyRu: 'В английском нельзя без am/is/are!' },
      { wrong: 'She are tall.', right: 'She is tall.', whyRu: 'She — это одна она, значит is, а не are.' },
    ],
    tip: 'Запомни: I — всегда am. He/She/It (один предмет) — is. Мы/Вы/Они (много) — are.',
  },
  {
    id: 'gr_present_simple',
    topic: 'present_simple',
    titleEn: 'Present Simple',
    titleRu: 'Простое настоящее время',
    level: '3-4',
    explanation: 'Present Simple — это то, что ты делаешь обычно, каждый день, всегда. По-русски: «Я хожу в школу», «Мама готовит обед», «Кошки любят рыбу». Это не прямо сейчас, а вообще, обычно.',
    ruAnalogy: 'Русское «Я читаю книги» (вообще, как привычка) = I read books. А «Я сейчас читаю» — это уже другое время!',
    formula: 'I/You/We/They → глагол без изменений  |  He/She/It → глагол + s',
    examples: [
      { en: 'I play football.', ru: 'Я играю в футбол (вообще, как хобби).', highlight: 'play' },
      { en: 'She plays piano.', ru: 'Она играет на пианино (регулярно).', highlight: 'plays' },
      { en: 'We go to school.', ru: 'Мы ходим в школу (каждый день).', highlight: 'go' },
      { en: 'He likes ice cream.', ru: 'Он любит мороженое (всегда).', highlight: 'likes' },
      { en: 'Cats sleep a lot.', ru: 'Кошки много спят (вообще).', highlight: 'sleep' },
    ],
    antiExamples: [
      { wrong: 'She play tennis.', right: 'She plays tennis.', whyRu: 'После he/she/it к глаголу добавляем -s!' },
      { wrong: 'I plays guitar.', right: 'I play guitar.', whyRu: 'После I не нужно -s.' },
    ],
    tip: 'Правило «один он/она/оно — добавь s»: He reads, She eats, It rains. Слова-маркеры: always, usually, every day, often.',
  },
  {
    id: 'gr_present_continuous',
    topic: 'present_continuous',
    titleEn: 'Present Continuous',
    titleRu: 'Настоящее длительное время',
    level: '3-4',
    explanation: 'Present Continuous — это то, что происходит прямо сейчас, в этот момент. По-русски: «Я сейчас читаю», «Мама сейчас готовит», «Смотри, дети играют!». Ключевое слово — СЕЙЧАС.',
    ruAnalogy: 'Русское «Я сейчас читаю книгу» (прямо в этот момент) = I am reading a book. Если без «сейчас» и это привычка — то Present Simple.',
    formula: 'am/is/are + глагол + ing',
    examples: [
      { en: 'I am reading a book.', ru: 'Я читаю книгу (прямо сейчас).', highlight: 'am reading' },
      { en: 'She is cooking dinner.', ru: 'Она готовит обед (прямо сейчас).', highlight: 'is cooking' },
      { en: 'They are playing in the park.', ru: 'Они играют в парке (сейчас, я их вижу).', highlight: 'are playing' },
      { en: 'Look! It is raining!', ru: 'Смотри! Идёт дождь!', highlight: 'is raining' },
      { en: 'We are watching TV.', ru: 'Мы смотрим телевизор (сейчас).', highlight: 'are watching' },
    ],
    antiExamples: [
      { wrong: 'She cooking.', right: 'She is cooking.', whyRu: 'Нужен am/is/are перед глаголом с -ing!' },
      { wrong: 'I am read.', right: 'I am reading.', whyRu: 'Нужно добавить -ing к глаголу!' },
    ],
    tip: 'Слова-подсказки: now, right now, at the moment, Look!, Listen! Если видишь их — это Present Continuous.',
  },
  {
    id: 'gr_past_simple',
    topic: 'past_simple',
    titleEn: 'Past Simple',
    titleRu: 'Простое прошедшее время',
    level: '4-5',
    explanation: 'Past Simple — это то, что уже произошло и закончилось. Вчера, на прошлой неделе, в прошлом году. По-русски: «Я ходил в школу», «Мы играли в парке», «Она купила мороженое».',
    ruAnalogy: 'Русское «Я вчера смотрел фильм» = I watched a film yesterday. Действие закончилось, осталось в прошлом.',
    formula: 'Правильные глаголы: глагол + ed  |  Неправильные: 2-я форма (went, saw, ate...)',
    examples: [
      { en: 'I played football yesterday.', ru: 'Я вчера играл в футбол.', highlight: 'played' },
      { en: 'She watched a film.', ru: 'Она посмотрела фильм.', highlight: 'watched' },
      { en: 'We went to the park.', ru: 'Мы ходили в парк.', highlight: 'went' },
      { en: 'He ate pizza for lunch.', ru: 'Он съел пиццу на обед.', highlight: 'ate' },
      { en: 'They saw a big dog.', ru: 'Они увидели большую собаку.', highlight: 'saw' },
    ],
    antiExamples: [
      { wrong: 'I goed to school.', right: 'I went to school.', whyRu: 'go — неправильный глагол! Прошедшее — went, а не goed.' },
      { wrong: 'She plaied tennis.', right: 'She played tennis.', whyRu: 'play + ed = played (не plaied).' },
    ],
    tip: 'Слова-подсказки: yesterday, last week, last year, ago, in 2020. Неправильные глаголы нужно учить наизусть — go→went, see→saw, eat→ate.',
  },
  {
    id: 'gr_can',
    topic: 'can_cant',
    titleEn: 'Can / Can\'t',
    titleRu: 'Умею / Не умею',
    level: '2-3',
    explanation: 'Can — значит «могу» или «умею». Can\'t — «не могу» или «не умею». Это очень простое слово! После can глагол идёт без изменений — никаких s или to. Просто: I can swim, She can dance, He can\'t fly.',
    ruAnalogy: 'Русское «Я умею плавать» = I can swim. «Я не умею летать» = I can\'t fly. Can одинаковый для всех — I can, he can, they can.',
    formula: 'can + глагол (без to, без s)  |  Вопрос: Can you...?',
    examples: [
      { en: 'I can swim.', ru: 'Я умею плавать.', highlight: 'can swim' },
      { en: 'She can dance very well.', ru: 'Она очень хорошо танцует.', highlight: 'can dance' },
      { en: 'He can\'t fly.', ru: 'Он не умеет летать.', highlight: 'can\'t fly' },
      { en: 'Can you ride a bike?', ru: 'Ты умеешь ездить на велосипеде?', highlight: 'Can you' },
      { en: 'Birds can fly.', ru: 'Птицы умеют летать.', highlight: 'can fly' },
    ],
    tip: 'Can никогда не меняется! Не бывает «cans» или «can to». Просто can + глагол.',
  },
  {
    id: 'gr_have_got',
    topic: 'have_got',
    titleEn: 'Have got / Has got',
    titleRu: 'У меня есть — have got',
    level: '2-3',
    explanation: 'Have got / has got означает «иметь». По-русски мы говорим «У меня ЕСТЬ кот», а по-английски: I HAVE GOT a cat. Для he/she/it — HAS GOT. Это одно из первых выражений, которое учат в школе!',
    ruAnalogy: 'Русское «У меня есть» = I have got. «У него есть» = He has got. Got можно опустить в американском английском.',
    formula: 'I/You/We/They → have got  |  He/She/It → has got',
    examples: [
      { en: 'I have got a cat.', ru: 'У меня есть кот.', highlight: 'have got' },
      { en: 'She has got blue eyes.', ru: 'У неё голубые глаза.', highlight: 'has got' },
      { en: 'We have got a big house.', ru: 'У нас есть большой дом.', highlight: 'have got' },
      { en: 'He has got a red bike.', ru: 'У него есть красный велосипед.', highlight: 'has got' },
      { en: 'Have you got a pet?', ru: 'У тебя есть питомец?', highlight: 'Have you got' },
    ],
    antiExamples: [
      { wrong: 'She have got a dog.', right: 'She has got a dog.', whyRu: 'She — значит has, а не have!' },
      { wrong: 'I has got a ball.', right: 'I have got a ball.', whyRu: 'I — всегда have.' },
    ],
    tip: 'Have got для I/you/we/they. Has got для he/she/it. Вопрос: Have you got...? Has she got...?',
  },
  {
    id: 'gr_there_is_are',
    topic: 'there_is_are',
    titleEn: 'There is / There are',
    titleRu: 'Есть, находится — there is / are',
    level: '2-3',
    explanation: 'There is/are используется, когда мы говорим, что что-то ГДЕ-ТО ЕСТЬ. «В комнате ЕСТЬ стол» = There IS a table in the room. Если предметов много — There ARE: There are two cats.',
    ruAnalogy: 'Русское «На столе стоит лампа» = There is a lamp on the table. «В парке есть деревья» = There are trees in the park.',
    formula: 'There is + один предмет  |  There are + много предметов',
    examples: [
      { en: 'There is a cat in the garden.', ru: 'В саду есть кот.', highlight: 'There is' },
      { en: 'There are three books on the desk.', ru: 'На парте три книги.', highlight: 'There are' },
      { en: 'There is milk in the fridge.', ru: 'В холодильнике есть молоко.', highlight: 'There is' },
      { en: 'There are many toys in the box.', ru: 'В коробке много игрушек.', highlight: 'There are' },
      { en: 'Is there a park near your house?', ru: 'Рядом с твоим домом есть парк?', highlight: 'Is there' },
    ],
    antiExamples: [
      { wrong: 'There are a lamp.', right: 'There is a lamp.', whyRu: 'Лампа одна — значит is!' },
      { wrong: 'There is three cats.', right: 'There are three cats.', whyRu: 'Кошек три — значит are!' },
    ],
    tip: 'Один предмет — is. Много — are. Считай предметы!',
  },
  {
    id: 'gr_plurals',
    topic: 'plurals',
    titleEn: 'Plurals',
    titleRu: 'Множественное число',
    level: '2-3',
    explanation: 'Чтобы сказать «много» по-английски, обычно добавляем -S к слову: cat → cats, dog → dogs. Если слово кончается на -s, -sh, -ch, -x — добавляем -ES: bus → buses, box → boxes. А некоторые слова меняются целиком: child → children, man → men, foot → feet.',
    ruAnalogy: 'Как в русском: кот → коты, но ребёнок → дети (неправильная форма). В английском тоже есть исключения!',
    formula: 'Обычно: + s  |  После s/sh/ch/x: + es  |  Исключения: child→children, man→men, foot→feet',
    examples: [
      { en: 'one cat → two cats', ru: 'один кот → два кота', highlight: 'cats' },
      { en: 'one bus → two buses', ru: 'один автобус → два автобуса', highlight: 'buses' },
      { en: 'one box → two boxes', ru: 'одна коробка → две коробки', highlight: 'boxes' },
      { en: 'one child → two children', ru: 'один ребёнок → двое детей', highlight: 'children' },
      { en: 'one man → two men', ru: 'один мужчина → двое мужчин', highlight: 'men' },
    ],
    tip: 'Большинство слов: просто +s. После шипящих: +es. Исключения учи наизусть: children, men, women, feet, teeth, mice.',
  },
  {
    id: 'gr_possessives',
    topic: 'possessives',
    titleEn: 'Possessives — my, your, his, her',
    titleRu: 'Притяжательные — мой, твой, его, её',
    level: '2-3',
    explanation: 'Притяжательные местоимения показывают, КОМУ принадлежит предмет. My = мой, your = твой, his = его, her = её, its = его/её (для вещей), our = наш, their = их. Они стоят ПЕРЕД существительным: my cat, her book.',
    ruAnalogy: 'Как русские «мой, твой, его, её, наш, их». My book = моя книга, their house = их дом.',
    formula: 'I → my  |  you → your  |  he → his  |  she → her  |  it → its  |  we → our  |  they → their',
    examples: [
      { en: 'This is my cat.', ru: 'Это мой кот.', highlight: 'my' },
      { en: 'Her name is Anna.', ru: 'Её зовут Анна.', highlight: 'Her' },
      { en: 'His dog is big.', ru: 'Его собака большая.', highlight: 'His' },
      { en: 'Our school is nice.', ru: 'Наша школа хорошая.', highlight: 'Our' },
      { en: 'Their house is big.', ru: 'Их дом большой.', highlight: 'Their' },
    ],
    antiExamples: [
      { wrong: 'He book is on the desk.', right: 'His book is on the desk.', whyRu: 'He — это «он», а «его» — his!' },
      { wrong: 'She name is Masha.', right: 'Her name is Masha.', whyRu: 'She — «она», а «её» — her!' },
    ],
    tip: 'Не путай he и his, she и her! He plays (он играет) vs His ball (его мяч).',
  },
  {
    id: 'gr_this_that',
    topic: 'this_that',
    titleEn: 'This / That / These / Those',
    titleRu: 'Это / То — this, that, these, those',
    level: '2-3',
    explanation: 'This = это (близко, один предмет). That = то (далеко, один предмет). These = эти (близко, много). Those = те (далеко, много). Представь: ты указываешь на вещи рядом (this/these) или вдалеке (that/those).',
    ruAnalogy: 'This = это (рядом). That = то (далеко). These = эти (рядом, много). Those = те (далеко, много).',
    formula: 'Близко: this (1) / these (много)  |  Далеко: that (1) / those (много)',
    examples: [
      { en: 'This is my pencil.', ru: 'Это мой карандаш (он у меня).', highlight: 'This' },
      { en: 'That is a big tree.', ru: 'То большое дерево (далеко).', highlight: 'That' },
      { en: 'These are my toys.', ru: 'Это мои игрушки (они тут).', highlight: 'These' },
      { en: 'Those books are interesting.', ru: 'Те книги интересные (на полке).', highlight: 'Those' },
    ],
    antiExamples: [
      { wrong: 'These is my book.', right: 'This is my book.', whyRu: 'Книга одна — this, а не these!' },
      { wrong: 'This are my cats.', right: 'These are my cats.', whyRu: 'Кошек много — these + are!' },
    ],
    tip: 'Один предмет: this/that + is. Много: these/those + are.',
  },
  {
    id: 'gr_prepositions',
    topic: 'prepositions',
    titleEn: 'Prepositions — in, on, under, next to',
    titleRu: 'Предлоги места — in, on, under, next to',
    level: '2-3',
    explanation: 'Предлоги говорят, ГДЕ находится предмет. In = в (in the box — в коробке). On = на (on the table — на столе). Under = под (under the bed — под кроватью). Next to = рядом с (next to the door — рядом с дверью). Behind = за. In front of = перед.',
    ruAnalogy: 'In = в, on = на, under = под, next to = рядом с, behind = за, in front of = перед.',
    formula: 'in (внутри) | on (на поверхности) | under (под) | next to (рядом) | behind (за) | in front of (перед)',
    examples: [
      { en: 'The cat is in the box.', ru: 'Кот в коробке.', highlight: 'in' },
      { en: 'The book is on the table.', ru: 'Книга на столе.', highlight: 'on' },
      { en: 'The dog is under the bed.', ru: 'Собака под кроватью.', highlight: 'under' },
      { en: 'She is next to the window.', ru: 'Она рядом с окном.', highlight: 'next to' },
      { en: 'The ball is behind the chair.', ru: 'Мяч за стулом.', highlight: 'behind' },
    ],
    tip: 'IN = внутри чего-то. ON = лежит на поверхности. UNDER = под чем-то.',
  },
  {
    id: 'gr_imperatives',
    topic: 'imperatives',
    titleEn: 'Imperatives — commands',
    titleRu: 'Повелительное наклонение — команды',
    level: '2-3',
    explanation: 'Imperative — это когда ты просишь или приказываешь кому-то что-то сделать. В английском это очень просто: бери глагол и ставь его первым! Sit down! Stand up! Open your book! Для «не делай» добавляем Don\'t: Don\'t run! Don\'t talk!',
    ruAnalogy: 'Русское «Сядь!» = Sit down! «Открой книгу!» = Open your book! «Не бегай!» = Don\'t run!',
    formula: 'Глагол! (делай)  |  Don\'t + глагол! (не делай)',
    examples: [
      { en: 'Sit down, please.', ru: 'Садитесь, пожалуйста.', highlight: 'Sit down' },
      { en: 'Open your book.', ru: 'Откройте книгу.', highlight: 'Open' },
      { en: 'Stand up!', ru: 'Встаньте!', highlight: 'Stand up' },
      { en: "Don't run in the classroom!", ru: 'Не бегайте в классе!', highlight: "Don't run" },
      { en: 'Listen and repeat.', ru: 'Слушайте и повторяйте.', highlight: 'Listen' },
    ],
    tip: 'Imperative = глагол без «to», без подлежащего. Sit! Run! Read! Don\'t talk!',
  },
];
