import type { SpotlightModule, SpotlightWord } from '../types';

function w(word: string, translation: string, pos = 'noun', diff: 1 | 2 | 3 = 1, phonics?: string): SpotlightWord {
  return { word, translation, image: `vocabulary/${word.replace(/\s+/g, '-')}.svg`, phonicsRule: phonics, partOfSpeech: pos, difficulty: diff };
}

export const SPOTLIGHT_2_MODULES: SpotlightModule[] = [
  {
    id: 'starter_letters',
    title: 'Starter: My Letters!',
    titleRu: 'Вводный модуль: Мои буквы!',
    grade: 2,
    order: 0,
    words: [
      w('ant', 'муравей', 'noun', 1, 'short_a'), w('bed', 'кровать', 'noun', 1, 'short_e'),
      w('cat', 'кот', 'noun', 1, 'short_a'), w('dog', 'собака', 'noun', 1, 'short_o'),
      w('egg', 'яйцо', 'noun', 1, 'short_e'), w('flag', 'флаг', 'noun', 1, 'consonant_blend_fl'),
      w('glass', 'стакан', 'noun', 1, 'consonant_blend_gl'), w('horse', 'лошадь', 'noun', 2, 'r_controlled_or'),
      w('ink', 'чернила', 'noun', 1, 'short_i'), w('jug', 'кувшин', 'noun', 1, 'short_u'),
      w('kangaroo', 'кенгуру', 'noun', 2), w('lamp', 'лампа', 'noun', 1, 'short_a'),
      w('mouse', 'мышь', 'noun', 2), w('nest', 'гнездо', 'noun', 1, 'short_e'),
      w('orange', 'апельсин', 'noun', 2), w('pen', 'ручка', 'noun', 1, 'short_e'),
      w('queen', 'королева', 'noun', 2, 'vowel_team_ee'), w('rabbit', 'кролик'),
      w('snake', 'змея', 'noun', 2, 'long_a_e'), w('tree', 'дерево', 'noun', 1, 'vowel_team_ee'),
      w('umbrella', 'зонт', 'noun', 2, 'short_u'), w('vest', 'жилет', 'noun', 1, 'short_e'),
      w('window', 'окно', 'noun', 2), w('box', 'коробка', 'noun', 1, 'short_o'),
      w('yacht', 'яхта', 'noun', 3), w('zip', 'молния', 'noun', 1, 'short_i'),
    ],
    phrases: [
      { phrase: 'Hello!', translation: 'Привет!', context: 'Приветствие' },
      { phrase: 'What\'s your name?', translation: 'Как тебя зовут?', context: 'Знакомство' },
      { phrase: 'My name is...', translation: 'Меня зовут...', context: 'Знакомство' },
    ],
    sentences: [
      { sentence: 'Hello! I\'m Larry.', translation: 'Привет! Я Ларри.', highlightWords: ['Hello', 'I\'m'] },
      { sentence: 'This is Chuckles.', translation: 'Это Чаклз.', highlightWords: ['This', 'is'] },
    ],
    grammar: ['I\'m = I am', 'What\'s = What is', 'This is...'],
    texts: [
      {
        title: 'Meet Larry and Lulu',
        titleRu: 'Знакомьтесь: Ларри и Лулу',
        lines: [
          'Hello! My name is Larry.',
          'I am a boy.',
          'This is Lulu. She is a girl.',
          'And this is Chuckles!',
          'He is funny!',
          'We are friends.',
        ],
      },
      {
        title: 'My Favourite Things',
        titleRu: 'Мои любимые вещи',
        lines: [
          'I am Lulu.',
          'This is my cat. My cat is on the bed.',
          'This is my dog. My dog is big.',
          'I like my cat and my dog.',
          'They are my friends!',
        ],
      },
    ],
  },
  {
    id: 'starter_numbers_colours',
    title: 'Starter: My Numbers & Colours!',
    titleRu: 'Вводный модуль: Числа и цвета!',
    grade: 2,
    order: 1,
    words: [
      w('one', 'один', 'number'), w('two', 'два', 'number'), w('three', 'три', 'number', 1, 'digraph_th'),
      w('four', 'четыре', 'number'), w('five', 'пять', 'number', 1, 'long_i_e'),
      w('six', 'шесть', 'number', 1, 'short_i'), w('seven', 'семь', 'number'),
      w('eight', 'восемь', 'number', 2), w('nine', 'девять', 'number', 1, 'long_i_e'),
      w('ten', 'десять', 'number', 1, 'short_e'),
      w('red', 'красный', 'color', 1, 'short_e'), w('blue', 'синий', 'color'),
      w('green', 'зелёный', 'color', 1, 'vowel_team_ee'), w('yellow', 'жёлтый', 'color', 2),
      w('orange', 'оранжевый', 'color', 2), w('pink', 'розовый', 'color', 1, 'short_i'),
      w('black', 'чёрный', 'color', 1, 'consonant_blend_bl'), w('white', 'белый', 'color', 1, 'long_i_e'),
      w('brown', 'коричневый', 'color', 2, 'consonant_blend_br'), w('purple', 'фиолетовый', 'color', 2, 'r_controlled_ur'),
    ],
    phrases: [
      { phrase: 'How many?', translation: 'Сколько?', context: 'Количество' },
      { phrase: 'What colour is it?', translation: 'Какого это цвета?', context: 'Цвет' },
    ],
    sentences: [
      { sentence: 'I can see three cats.', translation: 'Я вижу трёх котов.', highlightWords: ['three', 'cats'] },
      { sentence: 'The ball is red.', translation: 'Мяч красный.', highlightWords: ['ball', 'red'] },
    ],
    grammar: ['How many + сущ?', 'What colour is it? — It\'s...', 'I can see...'],
    texts: [
      {
        title: 'My Colourful Room',
        titleRu: 'Моя разноцветная комната',
        lines: [
          'I can see many colours in my room.',
          'My bed is blue. My lamp is yellow.',
          'I have got three red books and two green pens.',
          'How many orange balls? One, two, three! Three orange balls!',
          'I like colours!',
        ],
      },
    ],
  },
  {
    id: 'module_1_my_home',
    title: 'Module 1: My Home!',
    titleRu: 'Модуль 1: Мой дом!',
    grade: 2,
    order: 2,
    words: [
      w('house', 'дом'), w('bedroom', 'спальня', 'noun', 2), w('kitchen', 'кухня', 'noun', 2, 'digraph_ch'),
      w('bathroom', 'ванная', 'noun', 2, 'digraph_th'), w('living room', 'гостиная', 'noun', 2),
      w('garden', 'сад', 'noun', 2, 'r_controlled_ar'),
      w('table', 'стол', 'noun', 1, 'long_a_e'), w('chair', 'стул', 'noun', 1, 'digraph_ch'),
      w('bed', 'кровать', 'noun', 1, 'short_e'), w('door', 'дверь', 'noun', 1, 'r_controlled_or'),
      w('window', 'окно', 'noun', 2), w('lamp', 'лампа', 'noun', 1, 'short_a'),
      w('in', 'в', 'preposition'), w('on', 'на', 'preposition'), w('under', 'под', 'preposition'),
    ],
    phrases: [
      { phrase: 'Where\'s Chuckles?', translation: 'Где Чаклз?', context: 'Местоположение' },
      { phrase: 'He\'s in the kitchen.', translation: 'Он на кухне.', context: 'Ответ' },
    ],
    sentences: [
      { sentence: 'Mummy is in the kitchen.', translation: 'Мама на кухне.', highlightWords: ['Mummy', 'kitchen'] },
      { sentence: 'The cat is under the table.', translation: 'Кот под столом.', highlightWords: ['cat', 'under', 'table'] },
    ],
    grammar: ['Where\'s = Where is', 'He\'s/She\'s in...', 'Предлоги: in, on, under'],
    texts: [
      {
        title: 'My House',
        titleRu: 'Мой дом',
        lines: [
          'This is my house. It is big!',
          'There is a kitchen and a living room.',
          'My bedroom is nice. The lamp is on the table.',
          'Where is Chuckles? He is under the bed!',
          'Mummy is in the kitchen. Daddy is in the garden.',
        ],
      },
      {
        title: 'Where Is My Cat?',
        titleRu: 'Где мой кот?',
        lines: [
          'Where is my cat?',
          'Is he in the bedroom? No!',
          'Is he in the bathroom? No!',
          'Is he in the kitchen? No!',
          'Oh! He is on the chair in the living room!',
        ],
      },
    ],
  },
  {
    id: 'module_2_my_birthday',
    title: 'Module 2: My Birthday!',
    titleRu: 'Модуль 2: Мой день рождения!',
    grade: 2,
    order: 3,
    words: [
      w('happy', 'счастливый', 'adjective'), w('sad', 'грустный', 'adjective', 1, 'short_a'),
      w('birthday', 'день рождения', 'noun', 2, 'digraph_th'), w('cake', 'торт', 'noun', 1, 'long_a_e'),
      w('present', 'подарок', 'noun', 2), w('balloon', 'воздушный шар', 'noun', 2),
      w('chocolate', 'шоколад', 'noun', 2, 'digraph_ch'), w('ice cream', 'мороженое', 'noun', 1, 'long_i_e'),
      w('pizza', 'пицца'), w('juice', 'сок', 'noun', 2), w('milk', 'молоко', 'noun', 1, 'short_i'),
      w('apple', 'яблоко'), w('banana', 'банан'),
    ],
    phrases: [
      { phrase: 'Happy birthday!', translation: 'С днём рождения!', context: 'Поздравление' },
      { phrase: 'How old are you?', translation: 'Сколько тебе лет?', context: 'Возраст' },
      { phrase: 'I like chocolate!', translation: 'Я люблю шоколад!', context: 'Предпочтения' },
    ],
    sentences: [
      { sentence: 'I\'m nine years old.', translation: 'Мне девять лет.', highlightWords: ['nine', 'years', 'old'] },
      { sentence: 'I like cake and ice cream.', translation: 'Я люблю торт и мороженое.', highlightWords: ['like', 'cake', 'ice cream'] },
    ],
    grammar: ['How old are you? — I\'m + число', 'I like... / I don\'t like...', 'Числа 1-20'],
    texts: [
      {
        title: 'Lulu\'s Birthday Party',
        titleRu: 'День рождения Лулу',
        lines: [
          'Today is Lulu\'s birthday. She is eight years old.',
          'Happy birthday, Lulu!',
          'There is a big cake and five balloons.',
          'I like chocolate and ice cream.',
          'Larry likes juice and pizza.',
          'We are happy! It is a great party!',
        ],
      },
    ],
  },
  {
    id: 'module_3_my_animals',
    title: 'Module 3: My Animals!',
    titleRu: 'Модуль 3: Мои животные!',
    grade: 2,
    order: 4,
    words: [
      w('fish', 'рыба', 'noun', 1, 'digraph_sh'), w('frog', 'лягушка', 'noun', 1, 'consonant_blend_fr'),
      w('bird', 'птица', 'noun', 1, 'r_controlled_ir'), w('chimp', 'шимпанзе', 'noun', 2, 'digraph_ch'),
      w('horse', 'лошадь', 'noun', 1, 'r_controlled_or'),
      w('swim', 'плавать', 'verb', 1, 'consonant_blend_sw'), w('sing', 'петь', 'verb', 1, 'digraph_ng'),
      w('jump', 'прыгать', 'verb', 1, 'short_u'), w('dance', 'танцевать', 'verb'),
      w('run', 'бегать', 'verb', 1, 'short_u'), w('climb', 'лазить', 'verb', 2),
      w('fly', 'летать', 'verb'), w('swing', 'качаться', 'verb', 1, 'consonant_blend_sw'),
      w('boy', 'мальчик', 'noun', 1), w('girl', 'девочка', 'noun', 1, 'r_controlled_ir'),
      w('clown', 'клоун', 'noun', 1), w('circus', 'цирк', 'noun', 2),
      w('magician', 'фокусник', 'noun', 3),
      w('cat', 'кот', 'noun', 1, 'short_a'), w('dog', 'собака', 'noun', 1, 'short_o'),
    ],
    phrases: [
      { phrase: 'I can jump like a frog.', translation: 'Я могу прыгать как лягушка.', context: '7a' },
      { phrase: 'I can jump too.', translation: 'Я тоже умею прыгать.', context: '7a' },
      { phrase: 'run like a horse', translation: 'бегать как лошадь', context: '7a' },
      { phrase: 'swim like a fish', translation: 'плавать как рыба', context: '7a' },
      { phrase: 'dance like a chimp', translation: 'танцевать как шимпанзе', context: '7a' },
      { phrase: 'sing like a bird', translation: 'петь как птица', context: '7a' },
      { phrase: 'Well done!', translation: 'Молодец!', context: '7a dialogue' },
      { phrase: 'Hurry, children!', translation: 'Скорее, дети!', context: '7a dialogue' },
      { phrase: 'Food\'s ready.', translation: 'Еда готова.', context: '7a dialogue' },
      { phrase: 'Can you jump?', translation: 'Ты умеешь прыгать?', context: '8a' },
      { phrase: 'Yes, I can.', translation: 'Да, умею.', context: '8a' },
      { phrase: 'No, I can\'t.', translation: 'Нет, не умею.', context: '8a' },
      { phrase: 'There is a clown at the circus.', translation: 'В цирке есть клоун.', context: '9b' },
      { phrase: 'There are dogs at the circus.', translation: 'В цирке есть собаки.', context: '9b' },
      { phrase: 'Look at me!', translation: 'Посмотри на меня!', context: '9b song' },
    ],
    sentences: [
      { sentence: 'A frog can jump.', translation: 'Лягушка умеет прыгать.', highlightWords: ['frog', 'can', 'jump'] },
      { sentence: 'A bird can fly and sing.', translation: 'Птица умеет летать и петь.', highlightWords: ['bird', 'fly', 'sing'] },
      { sentence: 'Can a horse run? Yes, it can.', translation: 'Лошадь умеет бегать? Да, умеет.', highlightWords: ['horse', 'run', 'can'] },
      { sentence: 'Can a frog fly? No, it can\'t.', translation: 'Лягушка умеет летать? Нет, не умеет.', highlightWords: ['frog', 'fly', 'can\'t'] },
      { sentence: 'Bob can dance.', translation: 'Боб умеет танцевать.', highlightWords: ['can', 'dance'] },
      { sentence: 'Chuckles can sing.', translation: 'Чаклз умеет петь.', highlightWords: ['can', 'sing'] },
      { sentence: 'Can you swim? Yes, I can.', translation: 'Ты умеешь плавать? Да, умею.', highlightWords: ['swim', 'can'] },
      { sentence: 'I can sing and I can dance.', translation: 'Я умею петь и танцевать.', highlightWords: ['can', 'sing', 'dance'] },
    ],
    grammar: [
      'can / can\'t (умею / не умею)',
      'Can you...? — Yes, I can. / No, I can\'t.',
      'I can jump like a frog. (сравнение с like)',
      'There is / There are (в цирке)',
    ],
    texts: [
      {
        title: '7a Dialogue: Nanny, look!',
        titleRu: '7a Диалог: Няня, смотри!',
        lines: [
          'Larry: Nanny, look! A fish. I can swim too!',
          'Nanny: Well done, Larry!',
          'Lulu: Nanny, look! A frog. I can jump too!',
          'Nanny: Well done, dear!',
          'Nanny: Hurry, children! Food\'s ready.',
          'Larry: Nanny, where\'s Chuckles?',
        ],
      },
      {
        title: '7b Song: I can jump like a frog',
        titleRu: '7b Песня: Я могу прыгать как лягушка',
        lines: [
          'I can jump like a frog, Boing, boing!',
          'I can swim like a fish, Splish, splash, splish!',
          'I can jump and I can swim,',
          'I can dance and I can sing!',
          'And I can run and run and run',
          'Just like this!',
        ],
      },
      {
        title: '8a Song: I can jump, I can run',
        titleRu: '8a Песня: Я умею прыгать, бегать',
        lines: [
          'I can jump, I can run, I can climb out in the sun!',
          'I can jump, I can run, I can swim out in the sun!',
          'I like dancing, jumping, swimming,',
          'singing, running, climbing trees!',
        ],
      },
      {
        title: '8b Dialogue: Where\'s Chuckles?',
        titleRu: '8b Диалог: Где Чаклз?',
        lines: [
          'Larry: Chuckles!',
          'Lulu: Chuckles, where are you?',
          'Larry: Look! There\'s Chuckles in the tree!',
          'Lulu: Can you climb the tree, Larry?',
          'Larry: No, I can\'t.',
          'Lulu: Look! Who\'s that?',
          'Larry: Ha, ha! It\'s a girl chimp.',
          'Lulu: Look, Nanny! Two chimps. A boy and a girl.',
          'Larry: Yes, Chuckles and Cherry! Ha, ha.',
          'Nanny: Oh dear!',
        ],
      },
      {
        title: '8b Song: Can you fly?',
        titleRu: '8b Песня: Ты умеешь летать?',
        lines: [
          'Can you fly? Can you fly? Can you fly? No, I can\'t!',
          'Can you climb? Can you climb? Can you climb? Yes, I can!',
          'Can you climb like a chimp? Can you fly like a bird?',
          'Can you climb? Yes, I can! Can you fly? No, I can\'t!',
        ],
      },
      {
        title: '9a Song: At the Circus',
        titleRu: '9a Песня: В цирке',
        lines: [
          'At the circus in the town, There\'s a very funny clown!',
          'The clown can run, And the clown can jump,',
          'Run and jump all day, Hey!',
          'At the circus in the town, There\'s a very funny chimp!',
          'The chimp can climb, And the chimp can swing,',
          'Climb and swing all day, Hey!',
        ],
      },
      {
        title: '9a Dialogue: Wow, the circus!',
        titleRu: '9a Диалог: Ура, цирк!',
        lines: [
          'Larry: Wow, the circus! Look, a clown.',
          'Lulu: Look, a magician.',
          'Magician: Cherry, Cherry, where are you?',
          'Nanny: Cherry\'s here!',
          'Magician: Oh, thank you! Do you want to come to the circus today?',
          'Larry & Lulu: Ooh, yes, please!',
          'Magician: Now, boys and girls! Look at Cherry. And... Abracadabra, Alacazam! Look!',
          'Nanny: Bravo! Bravo!',
        ],
      },
      {
        title: '9b Song: I\'m a horse!',
        titleRu: '9b Песня: Я лошадка!',
        lines: [
          'I\'m a horse! I\'m a horse! And I can jump, of course! Look at me! Look at me!',
          'I\'m a cat! I\'m a cat! And I can climb like that! Look at me! Look at me!',
          'I\'m a fish! I\'m a fish! And I can swim, splish, splish! Look at me! Look at me!',
          'I\'m a chimp! I\'m a chimp! And I can climb and swing! Look at me! Look at me!',
        ],
      },
      {
        title: 'Portfolio: I can...',
        titleRu: 'Портфолио: Я умею...',
        lines: [
          'I can sing and I can dance.',
          'I can jump like a frog too!',
        ],
      },
      {
        title: 'Spotlight on the UK: Crazy about Animals',
        titleRu: 'В фокусе: Британия. Без ума от животных',
        lines: [
          'People in the UK love animals, especially cats and dogs.',
          'Popular names for cats are: Fluffy, Sam, Kitty, Smokey and Tiger!',
          'Popular names for dogs are: Blackie, Max, Patch, Prince, Lucky and Spot!',
        ],
      },
      {
        title: 'Fun at School: Circus Performers',
        titleRu: 'Весело в школе: Артисты цирка',
        lines: [
          'Children like going to the circus. They are happy there.',
          'Clowns are very funny, they jump and run.',
          'Acrobats can climb, swing and fly.',
          'Magicians show a lot of tricks.',
          'Do you like the circus?',
        ],
      },
      {
        title: 'The Town Mouse & The Country Mouse (Part 3)',
        titleRu: 'Городская мышь и деревенская мышь (Часть 3)',
        lines: [
          'Town Mouse: Look at my living room! Look at my chair!',
          'And look at the table over there!',
          'Country Mouse: Oh my! Lots of food — It all looks so good!',
          'Town Mouse: Burgers and chips And milk and ice cream.',
          'Country Mouse: Oh, this can\'t be real, It must be a dream!',
        ],
      },
    ],
  },
  {
    id: 'module_4_my_toys',
    title: 'Module 4: My Toys!',
    titleRu: 'Модуль 4: Мои игрушки!',
    grade: 2,
    order: 5,
    words: [
      w('teddy bear', 'плюшевый мишка'), w('toy soldier', 'игрушечный солдатик', 'noun', 2),
      w('ballerina', 'балерина', 'noun', 2), w('doll', 'кукла'),
      w('toy box', 'коробка для игрушек', 'noun', 2), w('toy', 'игрушка'),
      w('shelf', 'полка', 'noun', 1, 'digraph_sh'), w('pink', 'розовый', 'adjective', 1, 'short_i'),
      w('in', 'в', 'preposition'), w('on', 'на', 'preposition'),
      w('under', 'под', 'preposition'), w('near', 'рядом', 'preposition'),
      w('dark hair', 'тёмные волосы', 'noun', 2), w('nose', 'нос', 'noun', 1, 'long_o_e'),
      w('eyes', 'глаза', 'noun', 1), w('mouth', 'рот', 'noun', 1),
      w('ears', 'уши', 'noun', 1, 'vowel_team_ea'),
      w('fair hair', 'светлые волосы', 'noun', 2, 'vowel_team_ai'),
      w('puppet', 'марионетка', 'noun', 2), w('jack-in-the-box', 'чёртик из коробки', 'noun', 3),
      w('big', 'большой', 'adjective', 1, 'short_i'), w('small', 'маленький', 'adjective', 1, 'consonant_blend_sm'),
    ],
    phrases: [
      { phrase: 'Where\'s the teddy bear?', translation: 'Где плюшевый мишка?', context: '10a' },
      { phrase: 'Is it under the table?', translation: 'Он под столом?', context: '10a' },
      { phrase: 'Is it on the shelf?', translation: 'Он на полке?', context: '10a' },
      { phrase: 'Is it in the toy box?', translation: 'Он в коробке для игрушек?', context: '10a' },
      { phrase: 'She\'s got blue eyes.', translation: 'У неё голубые глаза.', context: '11b' },
      { phrase: 'He\'s got dark hair.', translation: 'У него тёмные волосы.', context: '11b' },
      { phrase: 'I\'ve got two eyes.', translation: 'У меня два глаза.', context: '11a' },
      { phrase: 'He hasn\'t got any eyes!', translation: 'У него нет глаз!', context: '12a' },
      { phrase: 'She\'s very pretty!', translation: 'Она очень красивая!', context: '11b' },
      { phrase: 'He\'s wonderful!', translation: 'Он замечательный!', context: '11b' },
      { phrase: 'Clever Chuckles!', translation: 'Умный Чаклз!', context: '11b' },
      { phrase: 'Don\'t be sad!', translation: 'Не грусти!', context: '11b' },
    ],
    sentences: [
      { sentence: 'The teddy bear is on the table.', translation: 'Мишка на столе.', highlightWords: ['teddy bear', 'on', 'table'] },
      { sentence: 'The ballerina is near the shelf.', translation: 'Балерина рядом с полкой.', highlightWords: ['ballerina', 'near', 'shelf'] },
      { sentence: 'The toys are in the toy box.', translation: 'Игрушки в коробке.', highlightWords: ['toys', 'in', 'toy box'] },
      { sentence: 'She\'s got dark hair.', translation: 'У неё тёмные волосы.', highlightWords: ['She\'s', 'got', 'dark', 'hair'] },
      { sentence: 'He\'s got a small black nose.', translation: 'У него маленький чёрный нос.', highlightWords: ['got', 'small', 'black', 'nose'] },
      { sentence: 'I haven\'t got toes!', translation: 'У меня нет пальцев на ногах!', highlightWords: ['haven\'t', 'got', 'toes'] },
    ],
    grammar: [
      'Предлоги: in, on, under, near',
      'Is it in/on/under...? — Yes, it is. / No, it isn\'t.',
      'I\'ve got / He\'s got / She\'s got',
      'He/She hasn\'t got...',
      'Irregular plurals: foot-feet, mouse-mice, child-children, man-men',
    ],
    texts: [
      {
        title: '10a Dialogue: Where\'s the teddy bear?',
        titleRu: '10a Диалог: Где плюшевый мишка?',
        lines: [
          'Nanny: Oh, dear, Chuckles! What\'s the matter?',
          'Lulu: He can\'t find his teddy bear. Nanny, where\'s his teddy bear?',
          'Nanny: I don\'t know.',
          'Lulu: Is it under the table?',
          'Larry: No, it isn\'t!',
          'Lulu: Oh, where is it?',
          'Lulu: Is it on the shelf?',
          'Larry: No, it isn\'t.',
          'Nanny: What about the toy box? Is it in the toy box?',
          'Larry: Oh, look! My toy soldier!',
          'Lulu: And look! My ballerina!',
          'Nanny: But what about Chuckles\' teddy bear?',
        ],
      },
      {
        title: '10b Song: Toys for me!',
        titleRu: '10b Песня: Игрушки для меня!',
        lines: [
          'Toys for me, Toys for you, Toys for everyone!',
          'A pink ballerina, A blue toy soldier! We\'re all having fun!',
          'Toys for me, Toys for you, Toys for everyone!',
          'A brown teddy bear, A yellow doll! We\'re all having fun!',
        ],
      },
      {
        title: '11a Song: I\'ve got two eyes',
        titleRu: '11a Песня: У меня два глаза',
        lines: [
          'I\'ve got two eyes, A mouth and a nose!',
          'I\'ve got two feet, But I haven\'t got toes!',
          'Two hands, two ears, And lots of hair!',
          'What am I? I\'m a teddy bear!',
        ],
      },
      {
        title: '11b Dialogue: Look at my ballerina!',
        titleRu: '11b Диалог: Посмотри на мою балерину!',
        lines: [
          'Lulu: Nanny, look at my ballerina! She\'s got blue eyes!',
          'Nanny: Yes, she\'s very pretty!',
          'Larry: Look at my toy soldier! He\'s got dark hair!',
          'Nanny: Oh, yes. He\'s wonderful! But what about Chuckles\' teddy bear?',
          'Larry: Chuckles, what have you got? Is it your teddy bear?',
          'Lulu: Oh, clever Chuckles!',
          'Larry: Oh no! Look at the teddy bear!',
          'Nanny: Oh, Chuckles! Don\'t be sad!',
        ],
      },
      {
        title: '11b Song: In my toy box',
        titleRu: '11b Песня: В моей коробке с игрушками',
        lines: [
          'In my toy box I\'ve got a teddy bear,',
          'And a ballerina With long dark hair!',
          'In my toy box I\'ve got a soldier too!',
          'I\'ve got lots of toys For me and you!',
          'Look in my toy box, Come and see!',
          'Toys for you, Toys for me!',
        ],
      },
      {
        title: '12a Dialogue: Teddy\'s Wonderful!',
        titleRu: '12a Диалог: Мишка замечательный!',
        lines: [
          'Larry: Oh no! Teddy hasn\'t got any eyes!',
          'Nanny: Yes, he has!',
          'Nanny: He\'s got two big eyes.',
          'Lulu: But look, Nanny! He hasn\'t got a nose!',
          'Nanny: Yes, he has! He\'s got a small black nose.',
          'Larry: Oh, now Teddy\'s wonderful!',
          'Lulu: Now Chuckles is very happy. Thank you, Nanny!',
          'Larry: Thank you, Nanny!',
        ],
      },
      {
        title: 'Portfolio: My toy soldier',
        titleRu: 'Портфолио: Мой солдатик',
        lines: [
          'Look at my toy soldier.',
          'It\'s got two eyes, a nose and a mouth.',
          'It\'s got dark hair too.',
          'My toy soldier is very nice!',
        ],
      },
      {
        title: 'Spotlight on the UK: Teddy Bear Shops',
        titleRu: 'В фокусе: Британия. Магазины мишек',
        lines: [
          'In Great Britain children love teddy bears!',
          'You can see all kinds of teddy bears: big and small and all different colours.',
          'Some teddy bears wear clothes and hats too.',
          'They\'re very cute!',
        ],
      },
    ],
  },
  {
    id: 'module_5_my_holidays',
    title: 'Module 5: My Holidays!',
    titleRu: 'Модуль 5: Мои каникулы!',
    grade: 2,
    order: 6,
    words: [
      w('sunny', 'солнечно', 'adjective'), w('hot', 'жарко', 'adjective', 1, 'short_o'),
      w('windy', 'ветрено', 'adjective', 2), w('cold', 'холодно', 'adjective'),
      w('jacket', 'куртка', 'noun', 1), w('coat', 'пальто', 'noun', 1, 'vowel_team_oa'),
      w('hat', 'шапка', 'noun', 1, 'short_a'), w('shorts', 'шорты', 'noun', 1, 'digraph_sh'),
      w('T-shirt', 'футболка', 'noun', 1, 'digraph_sh'), w('socks', 'носки', 'noun', 1),
      w('jeans', 'джинсы', 'noun', 1), w('shoes', 'обувь', 'noun', 1, 'digraph_sh'),
      w('skirt', 'юбка', 'noun', 1, 'r_controlled_ir'),
      w('island', 'остров', 'noun', 2), w('boat', 'лодка', 'noun', 1, 'vowel_team_oa'),
      w('flowers', 'цветы', 'noun', 1), w('music', 'музыка', 'noun', 2),
      w('summer', 'лето'), w('autumn', 'осень', 'noun', 2),
      w('winter', 'зима'), w('spring', 'весна', 'noun', 1, 'consonant_blend_sp'),
    ],
    phrases: [
      { phrase: 'It\'s sunny today!', translation: 'Сегодня солнечно!', context: '13a' },
      { phrase: 'It\'s hot today!', translation: 'Сегодня жарко!', context: '13a' },
      { phrase: 'It\'s raining!', translation: 'Идёт дождь!', context: '13a' },
      { phrase: 'Put on your hat.', translation: 'Надень шапку.', context: '13a' },
      { phrase: 'Take off your jacket!', translation: 'Сними куртку!', context: '13a' },
      { phrase: 'I\'m wearing my hat!', translation: 'Я в шапке!', context: '13a' },
      { phrase: 'What\'s the weather like?', translation: 'Какая погода?', context: '14a' },
      { phrase: 'It\'s cold!', translation: 'Холодно!', context: '14a' },
      { phrase: 'It\'s windy!', translation: 'Ветрено!', context: '14a' },
      { phrase: 'Don\'t worry, children.', translation: 'Не волнуйтесь, дети.', context: '14b' },
      { phrase: 'Close your eyes!', translation: 'Закройте глаза!', context: '14b' },
      { phrase: 'Open your eyes!', translation: 'Откройте глаза!', context: '14b' },
      { phrase: 'It\'s a magic island.', translation: 'Это волшебный остров.', context: '14b' },
      { phrase: 'We\'re on our summer holiday!', translation: 'Мы на летних каникулах!', context: '15a' },
    ],
    sentences: [
      { sentence: 'It\'s sunny today. Put on your hat.', translation: 'Сегодня солнечно. Надень шапку.', highlightWords: ['sunny', 'Put on', 'hat'] },
      { sentence: 'It\'s raining! Put on your coat.', translation: 'Идёт дождь! Надень пальто.', highlightWords: ['raining', 'Put on', 'coat'] },
      { sentence: 'Take off your jacket! It\'s hot!', translation: 'Сними куртку! Жарко!', highlightWords: ['Take off', 'jacket', 'hot'] },
      { sentence: 'I\'m wearing my jeans and my T-shirt.', translation: 'На мне джинсы и футболка.', highlightWords: ['wearing', 'jeans', 'T-shirt'] },
      { sentence: 'It\'s a magic island!', translation: 'Это волшебный остров!', highlightWords: ['magic', 'island'] },
      { sentence: 'We\'re on our summer holiday!', translation: 'Мы на летних каникулах!', highlightWords: ['summer', 'holiday'] },
    ],
    grammar: [
      'It\'s sunny / hot / windy / cold / raining (погода)',
      'What\'s the weather like? — It\'s...',
      'Put on / Take off + одежда',
      'I\'m wearing... (на мне надето)',
      'Seasons: summer, autumn, winter, spring',
    ],
    texts: [
      {
        title: '13a Dialogue: On Holiday',
        titleRu: '13a Диалог: На каникулах',
        lines: [
          'Larry: It\'s sunny today! Can we go in the boat, Nanny?',
          'Nanny: Of course! We\'re on holiday!',
          'Larry: Look! I\'m wearing my hat!',
          'Lulu: Oh, Chuckles! Take off your jacket! It\'s hot today!',
          'Larry: I love summer holidays.',
          'Lulu: I love boats.',
          'Nanny: Yes, this is a lovely holiday.',
          'Larry: Oh no! What\'s that?',
          'Nanny: Oh dear! It\'s raining! Lulu, put on your hat.',
          'Lulu: Nanny, what can we do now?',
          'Larry: Nanny! Look at our boat!',
          'Lulu: Oh, Nanny! HELP!!',
        ],
      },
      {
        title: '13b Song: It\'s hot today',
        titleRu: '13b Песня: Сегодня жарко',
        lines: [
          'It\'s hot today, Put on your hat!',
          'Take off your jacket, It\'s hot!',
          'It\'s raining, it\'s raining, Put on your coat!',
          'It\'s raining cats and dogs!',
          'It\'s sunny today, I\'m wearing my hat!',
          'It\'s sunny, It\'s sunny today!',
        ],
      },
      {
        title: '14a Song: Magic Island',
        titleRu: '14a Песня: Волшебный остров',
        lines: [
          'Close your eyes, Count one, two, three,',
          'Come to my magic island with me!',
          'It\'s hot, it\'s cold, it\'s windy too,',
          'It\'s a magic island, Just for you!',
        ],
      },
      {
        title: '14b Dialogue: It\'s windy!',
        titleRu: '14b Диалог: Ветрено!',
        lines: [
          'Larry: Oh, it\'s windy now! It\'s cold!',
          'Lulu: Oh, Nanny! Please help!',
          'Nanny: Don\'t worry, children. Close your eyes!',
          'Nanny: Alright! Open your eyes now.',
          'Larry: Wow! What\'s that?',
          'Lulu: It\'s an island!',
          'Nanny: Yes! It\'s a magic island.',
          'Larry & Lulu: Oooh!',
        ],
      },
      {
        title: '14b Song: I\'m wearing my jeans',
        titleRu: '14b Песня: На мне мои джинсы',
        lines: [
          'I\'m wearing my jeans And my favourite T-shirt!',
          'I\'m wearing my hat And my favourite skirt!',
          'I\'m wearing my jacket, I\'m wearing my coat,',
          'We\'re sailing away In our sailing boat!',
          'Take off your socks, Take off your shoes,',
          'We\'re sailing away On a magic cruise!',
        ],
      },
      {
        title: '15a Song: Summer Holiday',
        titleRu: '15a Песня: Летние каникулы',
        lines: [
          'We\'re on our summer holiday, We\'re having lots of fun!',
          'We\'re on our summer holiday, We\'re playing in the sun!',
          'We love summer, We love the sun!',
          'We love summer, It\'s lots and lots of fun!',
        ],
      },
      {
        title: '15a Dialogue: A Magic Island!',
        titleRu: '15a Диалог: Волшебный остров!',
        lines: [
          'Lulu: Wow! This is a magic island!',
          'Larry: Look at the trees! Look at the flowers!',
          'Lulu: What\'s that?',
          'Larry: It\'s music, of course!',
          'Nanny: Let\'s go and see!',
          'Woman: Aloha! Welcome!',
          'Larry: A party! Great!',
          'Lulu: Let\'s dance.',
          'Larry & Lulu: We\'re on our summer holiday, we\'re having lots of fun!',
        ],
      },
      {
        title: 'Portfolio: My Summer Holiday',
        titleRu: 'Портфолио: Мои летние каникулы',
        lines: [
          'This is me on my summer holiday.',
          'I am wearing red shorts and a blue and white T-shirt.',
          'I\'m wearing a hat too.',
          'It\'s hot today.',
        ],
      },
      {
        title: 'Spotlight on the UK: Great Britain',
        titleRu: 'В фокусе: Великобритания',
        lines: [
          'Look at the British flag: it\'s red, blue and white.',
          'A lot of people go to Great Britain on holiday.',
          'People have a lot of fun there.',
          'They like visiting the capital city — London.',
          'In London they can see red buses, red telephone boxes and black cabs.',
          'The English like tea with milk. Do you like it?',
        ],
      },
      {
        title: 'The Town Mouse & The Country Mouse (Finale)',
        titleRu: 'Городская мышь и деревенская мышь (Финал)',
        lines: [
          'Country Mouse: I don\'t like it here! I want my nice house.',
          'This is no place For a country mouse!',
          'Country Mouse: My house is small, And a little bit shabby.',
          'But I like it here, I\'m very happy!',
          'I don\'t like the town, I don\'t like the dogs.',
          'I\'m staying at home With the ants and the frogs!',
        ],
      },
    ],
  },
  // ===== PART 2 =====
  {
    id: 'module_6_my_body',
    title: 'Module 6: My Body!',
    titleRu: 'Модуль 6: Моё тело!',
    grade: 2,
    order: 7,
    words: [
      w('head', 'голова', 'noun', 1, 'short_e'), w('body', 'тело'),
      w('arms', 'руки', 'noun', 1, 'r_controlled_ar'), w('legs', 'ноги', 'noun', 1, 'short_e'),
      w('hands', 'ладони'), w('feet', 'ступни', 'noun', 1, 'vowel_team_ee'),
      w('tummy', 'животик'), w('shoulders', 'плечи', 'noun', 2),
      w('knees', 'колени', 'noun', 2, 'vowel_team_ee'), w('toes', 'пальцы ног'),
      w('face', 'лицо', 'noun', 1, 'long_a_e'), w('eyes', 'глаза'),
      w('ears', 'уши', 'noun', 1, 'vowel_team_ea'), w('nose', 'нос', 'noun', 1, 'long_o_e'),
      w('mouth', 'рот'), w('hair', 'волосы', 'noun', 1, 'vowel_team_ai'),
      w('teeth', 'зубы', 'noun', 1, 'vowel_team_ee'),
      w('long', 'длинный', 'adjective'), w('short', 'короткий', 'adjective', 1, 'digraph_sh'),
      w('fair', 'светлый', 'adjective', 2, 'vowel_team_ai'),
    ],
    phrases: [
      { phrase: 'I\'ve got two eyes.', translation: 'У меня два глаза.', context: 'Тело' },
      { phrase: 'Touch your nose!', translation: 'Дотронься до носа!', context: 'Команда' },
      { phrase: 'Clap your hands!', translation: 'Похлопай в ладоши!', context: 'Команда' },
      { phrase: 'She\'s got long fair hair.', translation: 'У неё длинные светлые волосы.', context: 'Описание' },
    ],
    sentences: [
      { sentence: 'I\'ve got ten toes and ten fingers.', translation: 'У меня десять пальцев на ногах и на руках.', highlightWords: ['ten', 'toes', 'fingers'] },
      { sentence: 'Touch your head! Clap your hands!', translation: 'Дотронься до головы! Похлопай в ладоши!', highlightWords: ['Touch', 'head', 'Clap', 'hands'] },
      { sentence: 'She\'s got long dark hair and blue eyes.', translation: 'У неё длинные тёмные волосы и голубые глаза.', highlightWords: ['long', 'dark', 'hair', 'blue', 'eyes'] },
    ],
    grammar: ['I\'ve got / He\'s got / She\'s got', 'Has he/she got...?', 'Touch/Clap/Stamp + your + часть тела'],
    texts: [
      {
        title: 'Look at Me!',
        titleRu: 'Посмотри на меня!',
        lines: [
          'I have got two eyes and two ears.',
          'I have got one nose and one mouth.',
          'My hair is short and dark.',
          'I have got two arms and two legs.',
          'I have got ten toes on my feet!',
          'Touch your head! Clap your hands! Stamp your feet!',
        ],
      },
      {
        title: 'My Friend Tom',
        titleRu: 'Мой друг Том',
        lines: [
          'This is my friend Tom.',
          'He has got long fair hair and blue eyes.',
          'He has got a big nose and a funny face.',
          'His arms are long. His legs are long too.',
          'Tom is my best friend!',
        ],
      },
    ],
  },
  {
    id: 'module_7_i_can_sing',
    title: 'Module 7: I Can Sing!',
    titleRu: 'Модуль 7: Я умею петь!',
    grade: 2,
    order: 8,
    words: [
      w('sing', 'петь', 'verb', 1, 'digraph_ng'), w('dance', 'танцевать', 'verb'),
      w('swim', 'плавать', 'verb', 1, 'consonant_blend_sw'), w('jump', 'прыгать', 'verb', 1, 'short_u'),
      w('run', 'бегать', 'verb', 1, 'short_u'), w('climb', 'лазить', 'verb', 2),
      w('fly', 'летать', 'verb'), w('ride a bike', 'ездить на велосипеде', 'phrase', 2, 'long_i_e'),
      w('paint', 'рисовать', 'verb', 1, 'vowel_team_ai'), w('draw', 'рисовать', 'verb'),
      w('write', 'писать', 'verb', 1, 'long_i_e'), w('read', 'читать', 'verb', 1, 'vowel_team_ea'),
      w('count', 'считать', 'verb', 2), w('play', 'играть', 'verb', 1, 'vowel_team_ay'),
      w('cook', 'готовить', 'verb', 1, 'vowel_team_oo'),
    ],
    phrases: [
      { phrase: 'I can sing very well!', translation: 'Я очень хорошо пою!', context: 'Умения' },
      { phrase: 'Can you ride a bike?', translation: 'Ты умеешь ездить на велосипеде?', context: 'Вопрос' },
      { phrase: 'She can paint but she can\'t cook.', translation: 'Она умеет рисовать, но не умеет готовить.', context: 'Умения' },
    ],
    sentences: [
      { sentence: 'I can read and write in English.', translation: 'Я умею читать и писать по-английски.', highlightWords: ['can', 'read', 'write'] },
      { sentence: 'Larry can\'t cook.', translation: 'Ларри не умеет готовить.', highlightWords: ['can\'t', 'cook'] },
      { sentence: 'I can count to twenty.', translation: 'Я умею считать до двадцати.', highlightWords: ['count', 'twenty'] },
    ],
    grammar: ['can / can\'t для умений', 'Can you...? — Yes, I can. / No, I can\'t.', 'He/She can... but can\'t...'],
    texts: [
      {
        title: 'What Can You Do?',
        titleRu: 'Что ты умеешь делать?',
        lines: [
          'I can sing and dance very well.',
          'I can read and write in English.',
          'I can draw but I can\'t paint.',
          'My friend Larry can ride a bike.',
          'He can swim and climb too.',
          'But he can\'t cook! Can you cook?',
        ],
      },
    ],
  },
  {
    id: 'module_8_at_the_circus',
    title: 'Module 8: At the Circus!',
    titleRu: 'Модуль 8: В цирке!',
    grade: 2,
    order: 9,
    words: [
      w('clown', 'клоун'), w('circus', 'цирк', 'noun', 2),
      w('magician', 'фокусник', 'noun', 3), w('seal', 'тюлень', 'noun', 1, 'vowel_team_ea'),
      w('elephant', 'слон', 'noun', 2), w('monkey', 'обезьяна'),
      w('lion', 'лев'), w('tiger', 'тигр'), w('bear', 'медведь'),
      w('funny', 'смешной', 'adjective'), w('clever', 'умный', 'adjective', 2),
      w('scary', 'страшный', 'adjective', 2), w('strong', 'сильный', 'adjective'),
      w('friendly', 'дружелюбный', 'adjective', 2), w('amazing', 'удивительный', 'adjective', 2),
      w('brave', 'смелый', 'adjective', 2, 'consonant_blend_br'),
    ],
    phrases: [
      { phrase: 'Look at the clown! He\'s funny!', translation: 'Посмотри на клоуна! Он смешной!', context: 'Цирк' },
      { phrase: 'The seal can play with a ball.', translation: 'Тюлень умеет играть с мячом.', context: 'Описание' },
      { phrase: 'I like the circus!', translation: 'Мне нравится цирк!', context: 'Мнение' },
    ],
    sentences: [
      { sentence: 'The clown is funny! He can juggle.', translation: 'Клоун смешной! Он умеет жонглировать.', highlightWords: ['clown', 'funny', 'juggle'] },
      { sentence: 'The elephant is big and strong.', translation: 'Слон большой и сильный.', highlightWords: ['elephant', 'big', 'strong'] },
      { sentence: 'The lion is scary but the monkey is friendly.', translation: 'Лев страшный, а обезьяна дружелюбная.', highlightWords: ['lion', 'scary', 'monkey', 'friendly'] },
    ],
    grammar: ['He\'s/She\'s/It\'s + прилагательное', 'Look at the + сущ!', 'I like / I love'],
    texts: [
      {
        title: 'A Day at the Circus',
        titleRu: 'День в цирке',
        lines: [
          'We are at the circus today!',
          'Look at the clown! He is very funny.',
          'The elephant is big and strong. It can dance!',
          'The seal is clever. It can play with a ball.',
          'The monkey is small and friendly.',
          'The lion is scary but amazing!',
          'I love the circus!',
        ],
      },
    ],
  },
  {
    id: 'module_9_my_toys_p2',
    title: 'Module 9: My Toys! (Part 2)',
    titleRu: 'Модуль 9: Мои игрушки! (Часть 2)',
    grade: 2,
    order: 10,
    words: [
      w('robot', 'робот'), w('rocking horse', 'лошадка-качалка', 'noun', 2),
      w('drum', 'барабан', 'noun', 1, 'consonant_blend_dr'), w('guitar', 'гитара', 'noun', 2),
      w('piano', 'пианино', 'noun', 2), w('kite', 'воздушный змей', 'noun', 1, 'long_i_e'),
      w('puzzle', 'пазл', 'noun', 2), w('game', 'игра', 'noun', 1, 'long_a_e'),
      w('computer', 'компьютер', 'noun', 2),
      w('my', 'мой', 'pronoun'), w('your', 'твой', 'pronoun'),
      w('his', 'его', 'pronoun'), w('her', 'её', 'pronoun'),
      w('our', 'наш', 'pronoun', 2), w('their', 'их', 'pronoun', 2, 'digraph_th'),
    ],
    phrases: [
      { phrase: 'Whose is this?', translation: 'Чьё это?', context: 'Принадлежность' },
      { phrase: 'It\'s Larry\'s robot.', translation: 'Это робот Ларри.', context: 'Притяжательный падеж' },
      { phrase: 'Is this your kite?', translation: 'Это твой воздушный змей?', context: 'Вопрос' },
    ],
    sentences: [
      { sentence: 'This is my robot. It\'s new!', translation: 'Это мой робот. Он новый!', highlightWords: ['my', 'robot', 'new'] },
      { sentence: 'Whose is this kite? It\'s his.', translation: 'Чей это воздушный змей? Его.', highlightWords: ['Whose', 'kite', 'his'] },
      { sentence: 'Our puzzle is on the table.', translation: 'Наш пазл на столе.', highlightWords: ['Our', 'puzzle', 'table'] },
    ],
    grammar: ['Whose is this? — It\'s my/your/his/her...', 'Притяжательный падеж: Larry\'s', 'my, your, his, her, our, their'],
    texts: [
      {
        title: 'Whose Toys Are These?',
        titleRu: 'Чьи это игрушки?',
        lines: [
          'There are many toys in our room.',
          'Whose is this robot? It is Larry\'s robot.',
          'This kite is her kite. It is pink.',
          'Whose is this drum? It is his drum.',
          'Our puzzle is on the table.',
          'Their guitar is new and their piano is old.',
          'I like my toys and your toys too!',
        ],
      },
    ],
  },
  {
    id: 'module_10_we_love_summer',
    title: 'Module 10: We Love Summer!',
    titleRu: 'Модуль 10: Мы любим лето!',
    grade: 2,
    order: 11,
    words: [
      w('swim', 'плавать', 'verb', 1, 'consonant_blend_sw'), w('play', 'играть', 'verb', 1, 'vowel_team_ay'),
      w('eat', 'есть', 'verb', 1, 'vowel_team_ea'), w('drink', 'пить', 'verb', 1, 'consonant_blend_dr'),
      w('make', 'делать', 'verb', 1, 'long_a_e'), w('sleep', 'спать', 'verb', 1, 'vowel_team_ee'),
      w('wake up', 'просыпаться', 'verb', 2, 'long_a_e'), w('have fun', 'веселиться', 'phrase', 2),
      w('ice cream', 'мороженое', 'noun', 1, 'long_i_e'), w('lemonade', 'лимонад', 'noun', 2),
      w('water', 'вода'), w('fruit', 'фрукты'), w('watermelon', 'арбуз', 'noun', 2),
      w('park', 'парк', 'noun', 1, 'r_controlled_ar'), w('pool', 'бассейн', 'noun', 1, 'vowel_team_oo'),
      w('playground', 'площадка', 'noun', 2, 'vowel_team_ay'), w('camp', 'лагерь', 'noun', 2),
      w('garden', 'сад', 'noun', 1, 'r_controlled_ar'), w('forest', 'лес', 'noun', 2),
      w('mountain', 'гора', 'noun', 2), w('lake', 'озеро', 'noun', 1, 'long_a_e'),
      w('river', 'река', 'noun', 2),
    ],
    phrases: [
      { phrase: 'I\'m playing in the garden.', translation: 'Я играю в саду.', context: 'Действие' },
      { phrase: 'We\'re swimming in the sea.', translation: 'Мы плаваем в море.', context: 'Действие' },
      { phrase: 'What are you doing?', translation: 'Что ты делаешь?', context: 'Вопрос' },
      { phrase: 'She\'s eating ice cream.', translation: 'Она ест мороженое.', context: 'Действие' },
    ],
    sentences: [
      { sentence: 'In summer we swim in the lake.', translation: 'Летом мы плаваем в озере.', highlightWords: ['summer', 'swim', 'lake'] },
      { sentence: 'I\'m eating a watermelon. Yummy!', translation: 'Я ем арбуз. Вкусно!', highlightWords: ['eating', 'watermelon'] },
      { sentence: 'The children are playing in the park.', translation: 'Дети играют в парке.', highlightWords: ['children', 'playing', 'park'] },
      { sentence: 'We love summer! We have fun every day.', translation: 'Мы любим лето! Мы веселимся каждый день.', highlightWords: ['love', 'summer', 'fun'] },
    ],
    grammar: ['Present Continuous: I\'m swimming / She\'s eating', 'What are you doing? — I\'m + verb + -ing', 'Let\'s + глагол!'],
    texts: [
      {
        title: 'Our Summer Day',
        titleRu: 'Наш летний день',
        lines: [
          'It is summer! We love summer!',
          'Today we are at the park.',
          'I am eating a watermelon. It is very nice!',
          'Lulu is drinking lemonade.',
          'Larry is playing in the pool.',
          'We have fun every day in summer!',
        ],
      },
      {
        title: 'A Letter from Camp',
        titleRu: 'Письмо из лагеря',
        lines: [
          'Hello Mummy! I am at camp.',
          'It is sunny and hot today.',
          'I am swimming in the lake.',
          'My friends are playing in the garden.',
          'We eat fruit and drink water.',
          'We wake up and we play all day!',
          'I love camp!',
        ],
      },
    ],
  },
];
