import type { SpotlightModule, SpotlightWord } from '../types';

function w(word: string, translation: string, pos = 'noun', diff: 1 | 2 | 3 = 1, phonics?: string): SpotlightWord {
  return { word, translation, image: `vocabulary/${word.replace(/\s+/g, '-')}.svg`, phonicsRule: phonics, partOfSpeech: pos, difficulty: diff };
}

export const SPOTLIGHT_3_MODULES: SpotlightModule[] = [
  {
    id: 's3_school_days',
    title: 'Module 1: School Days!',
    titleRu: 'Модуль 1: Школьные дни!',
    grade: 3,
    order: 0,
    words: [
      w('school', 'школа'), w('pencil', 'карандаш'), w('ruler', 'линейка'),
      w('eraser', 'ластик', 'noun', 2), w('school bag', 'портфель'),
      w('book', 'книга'), w('desk', 'парта'), w('classroom', 'класс', 'noun', 2),
      w('teacher', 'учитель'), w('pupil', 'ученик'),
      w('art', 'рисование'), w('maths', 'математика', 'noun', 2),
      w('English', 'английский'), w('music', 'музыка'),
      w('PE', 'физкультура'), w('science', 'наука', 'noun', 2),
      w('lesson', 'урок'), w('read', 'читать', 'verb'), w('write', 'писать', 'verb'),
      w('count', 'считать', 'verb'),
    ],
    phrases: [
      { phrase: 'This is my school.', translation: 'Это моя школа.', context: 'Школа' },
      { phrase: 'I\'ve got a pencil.', translation: 'У меня есть карандаш.', context: 'Школьные принадлежности' },
      { phrase: 'What\'s this?', translation: 'Что это?', context: 'Вопрос' },
      { phrase: 'It\'s a ruler.', translation: 'Это линейка.', context: 'Ответ' },
    ],
    sentences: [
      { sentence: 'I go to school every day.', translation: 'Я хожу в школу каждый день.', highlightWords: ['go', 'school', 'every day'] },
      { sentence: 'My favourite subject is English.', translation: 'Мой любимый предмет — английский.', highlightWords: ['favourite', 'subject', 'English'] },
      { sentence: 'I can read and write in English.', translation: 'Я умею читать и писать по-английски.', highlightWords: ['can', 'read', 'write'] },
    ],
    grammar: ['This is / These are...', 'I\'ve got / I haven\'t got', 'What\'s this? — It\'s a...'],
    texts: [
      {
        title: 'My School',
        titleRu: 'Моя школа',
        lines: [
          'My name is Tom and I go to school every day.',
          'I have got a big school bag with many things inside.',
          'There is a pencil, a ruler and an eraser in my bag.',
          'I also have got books for English and Maths.',
          'My classroom is big and there are twenty desks in it.',
          'My teacher is Mrs Brown and she is very kind.',
          'My favourite lesson is art because I like to draw.',
          'After school I read books at home.',
        ],
      },
      {
        title: 'Our Classroom',
        titleRu: 'Наш класс',
        lines: [
          'This is our classroom at school.',
          'There are many desks and chairs for the pupils.',
          'We have got pencils, rulers and erasers on our desks.',
          'The teacher writes on the board with a marker.',
          'We read and write in our English lesson.',
          'In Maths we count and draw numbers.',
          'I like PE because we run and play games.',
        ],
      },
    ],
  },
  {
    id: 's3_family_moments',
    title: 'Module 2: Family Moments!',
    titleRu: 'Модуль 2: Семейные моменты!',
    grade: 3,
    order: 1,
    words: [
      w('family', 'семья'), w('mum', 'мама'), w('dad', 'папа'),
      w('brother', 'брат'), w('sister', 'сестра'),
      w('grandma', 'бабушка'), w('grandpa', 'дедушка'),
      w('baby', 'малыш'), w('cousin', 'двоюродный брат/сестра', 'noun', 2),
      w('uncle', 'дядя'), w('aunt', 'тётя'),
      w('happy', 'счастливый', 'adjective'), w('kind', 'добрый', 'adjective'),
      w('funny', 'смешной', 'adjective'), w('young', 'молодой', 'adjective'),
      w('old', 'старый', 'adjective'), w('tall', 'высокий', 'adjective'),
      w('short', 'низкий', 'adjective'),
    ],
    phrases: [
      { phrase: 'This is my family.', translation: 'Это моя семья.', context: 'Семья' },
      { phrase: 'She\'s my mum.', translation: 'Она моя мама.', context: 'Семья' },
      { phrase: 'He\'s got brown hair.', translation: 'У него каштановые волосы.', context: 'Описание' },
      { phrase: 'How old is she?', translation: 'Сколько ей лет?', context: 'Возраст' },
    ],
    sentences: [
      { sentence: 'My mum is kind and funny.', translation: 'Моя мама добрая и весёлая.', highlightWords: ['mum', 'kind', 'funny'] },
      { sentence: 'I\'ve got a brother and a sister.', translation: 'У меня есть брат и сестра.', highlightWords: ['brother', 'sister'] },
      { sentence: 'Grandma is old but very happy.', translation: 'Бабушка старая, но очень счастливая.', highlightWords: ['Grandma', 'old', 'happy'] },
    ],
    grammar: ['She\'s / He\'s = She is / He is', 'He\'s/She\'s got...', 'How old is he/she?'],
    texts: [
      {
        title: 'My Big Family',
        titleRu: 'Моя большая семья',
        lines: [
          'I have got a big family and I love them all.',
          'My mum is tall and she has got long brown hair.',
          'She is very kind and always happy.',
          'My dad is tall too and he is very funny.',
          'I have got a brother and a baby sister.',
          'My brother is ten years old and he is short.',
          'My grandma and grandpa live next to our house.',
          'Grandpa is old but he is always happy to play with us.',
        ],
      },
    ],
  },
  {
    id: 's3_all_things_i_like',
    title: 'Module 3: All the Things I Like!',
    titleRu: 'Модуль 3: Всё что я люблю!',
    grade: 3,
    order: 2,
    words: [
      w('like', 'любить/нравиться', 'verb'), w('love', 'обожать', 'verb'),
      w('play', 'играть', 'verb'), w('watch', 'смотреть', 'verb'),
      w('listen', 'слушать', 'verb'), w('read', 'читать', 'verb'),
      w('draw', 'рисовать', 'verb'), w('paint', 'красить', 'verb'),
      w('sing', 'петь', 'verb'), w('dance', 'танцевать', 'verb'),
      w('football', 'футбол'), w('basketball', 'баскетбол', 'noun', 2),
      w('tennis', 'теннис'), w('computer game', 'компьютерная игра', 'noun', 2),
      w('cartoon', 'мультфильм'), w('film', 'фильм'),
      w('story', 'история/рассказ'), w('jelly', 'желе'),
      w('vegetables', 'овощи', 'noun', 2), w('chocolate', 'шоколад'),
    ],
    phrases: [
      { phrase: 'I like football!', translation: 'Мне нравится футбол!', context: 'Предпочтения' },
      { phrase: 'I don\'t like vegetables.', translation: 'Я не люблю овощи.', context: 'Предпочтения' },
      { phrase: 'Do you like cartoons?', translation: 'Тебе нравятся мультики?', context: 'Вопрос' },
      { phrase: 'Yes, I do! / No, I don\'t.', translation: 'Да! / Нет.', context: 'Ответ' },
    ],
    sentences: [
      { sentence: 'I like ice cream but I don\'t like jelly.', translation: 'Я люблю мороженое, но не люблю желе.', highlightWords: ['like', 'don\'t like'] },
      { sentence: 'She likes painting and drawing.', translation: 'Она любит рисовать красками и карандашами.', highlightWords: ['likes', 'painting', 'drawing'] },
      { sentence: 'Do you like playing football?', translation: 'Тебе нравится играть в футбол?', highlightWords: ['Do', 'like', 'playing'] },
    ],
    grammar: ['I like / I don\'t like', 'Do you like...? — Yes, I do. / No, I don\'t.', 'He/She likes (с -s!)'],
    texts: [
      {
        title: 'What We Like',
        titleRu: 'Что мы любим',
        lines: [
          'My name is Anna and I like many things.',
          'I like painting and drawing pictures of animals.',
          'I love watching cartoons on TV in the evening.',
          'My brother likes playing football and basketball.',
          'He does not like reading books but I do.',
          'We both like chocolate and ice cream very much.',
          'Do you like vegetables? I don\'t like them at all!',
          'On Sundays we listen to music and sing songs together.',
        ],
      },
    ],
  },
  {
    id: 's3_come_in_and_play',
    title: 'Module 4: Come in and Play!',
    titleRu: 'Модуль 4: Заходи и играй!',
    grade: 3,
    order: 3,
    words: [
      w('room', 'комната'), w('floor', 'пол'), w('wall', 'стена'),
      w('sofa', 'диван'), w('bookcase', 'книжный шкаф', 'noun', 2),
      w('wardrobe', 'шкаф для одежды', 'noun', 2), w('mirror', 'зеркало'),
      w('picture', 'картина'), w('carpet', 'ковёр'),
      w('behind', 'за', 'preposition', 2), w('between', 'между', 'preposition', 2),
      w('next to', 'рядом с', 'preposition', 2), w('in front of', 'перед', 'preposition', 2),
      w('toy box', 'коробка с игрушками'), w('computer', 'компьютер'),
      w('radio', 'радио'), w('guitar', 'гитара', 'noun', 2),
      w('piano', 'пианино', 'noun', 2),
    ],
    phrases: [
      { phrase: 'Where\'s the teddy bear?', translation: 'Где плюшевый мишка?', context: 'Местоположение' },
      { phrase: 'It\'s behind the sofa.', translation: 'Он за диваном.', context: 'Ответ' },
      { phrase: 'There\'s a bookcase in my room.', translation: 'В моей комнате есть книжный шкаф.', context: 'Описание' },
    ],
    sentences: [
      { sentence: 'The cat is behind the sofa.', translation: 'Кот за диваном.', highlightWords: ['behind', 'sofa'] },
      { sentence: 'There is a mirror on the wall.', translation: 'На стене зеркало.', highlightWords: ['There is', 'mirror', 'wall'] },
      { sentence: 'My guitar is next to the bookcase.', translation: 'Моя гитара рядом с книжным шкафом.', highlightWords: ['next to', 'bookcase'] },
    ],
    grammar: ['There is / There are', 'Where\'s...? — It\'s behind/between/next to/in front of', 'Предлоги места'],
    texts: [
      {
        title: 'My Room',
        titleRu: 'Моя комната',
        lines: [
          'I have got a very nice room in our house.',
          'There is a big sofa next to the wall.',
          'My bookcase is between the sofa and the wardrobe.',
          'There is a beautiful picture on the wall above the sofa.',
          'My computer is on the desk in front of the mirror.',
          'There is a carpet on the floor and it is very soft.',
          'My toy box is behind the door.',
          'I like to play guitar in my room in the evening.',
        ],
      },
    ],
  },
  {
    id: 's3_furry_friends',
    title: 'Module 5: Furry Friends!',
    titleRu: 'Модуль 5: Пушистые друзья!',
    grade: 3,
    order: 4,
    words: [
      w('head', 'голова'), w('tail', 'хвост'), w('body', 'тело'),
      w('leg', 'нога'), w('paw', 'лапа'), w('wing', 'крыло'),
      w('beak', 'клюв', 'noun', 2), w('feather', 'перо', 'noun', 2),
      w('fur', 'мех'), w('hamster', 'хомяк'),
      w('parrot', 'попугай'), w('goldfish', 'золотая рыбка'),
      w('tortoise', 'черепаха', 'noun', 2), w('rabbit', 'кролик'),
      w('puppy', 'щенок'), w('kitten', 'котёнок'),
      w('clever', 'умный', 'adjective'), w('cute', 'милый', 'adjective'),
      w('friendly', 'дружелюбный', 'adjective', 2),
    ],
    phrases: [
      { phrase: 'My hamster has got a short tail.', translation: 'У моего хомяка короткий хвост.', context: 'Описание' },
      { phrase: 'It\'s got big eyes and long ears.', translation: 'У него большие глаза и длинные уши.', context: 'Описание' },
      { phrase: 'Has it got wings?', translation: 'У него есть крылья?', context: 'Вопрос' },
    ],
    sentences: [
      { sentence: 'The parrot has got a long tail and colourful feathers.', translation: 'У попугая длинный хвост и красочные перья.', highlightWords: ['parrot', 'tail', 'feathers'] },
      { sentence: 'My puppy is cute and friendly.', translation: 'Мой щенок милый и дружелюбный.', highlightWords: ['puppy', 'cute', 'friendly'] },
      { sentence: 'Has the tortoise got legs? Yes, it has!', translation: 'У черепахи есть ноги? Да!', highlightWords: ['Has', 'got', 'legs'] },
    ],
    grammar: ['It\'s got... / It hasn\'t got...', 'Has it got...? — Yes, it has. / No, it hasn\'t.', 'Части тела животных'],
    texts: [
      {
        title: 'Our Pets',
        titleRu: 'Наши питомцы',
        lines: [
          'We have got three pets at home and they are all different.',
          'My hamster is small and cute with a short tail.',
          'It has got soft brown fur and tiny black eyes.',
          'My sister has got a parrot with colourful feathers.',
          'The parrot has got a yellow beak and long green wings.',
          'It is very clever and can say some words.',
          'Our kitten is friendly and likes to play all day.',
          'It has got four white paws and a fluffy tail.',
        ],
      },
    ],
  },
  {
    id: 's3_home_sweet_home',
    title: 'Module 6: Home Sweet Home!',
    titleRu: 'Модуль 6: Дом, милый дом!',
    grade: 3,
    order: 5,
    words: [
      w('house', 'дом'), w('flat', 'квартира'),
      w('kitchen', 'кухня'), w('bathroom', 'ванная'),
      w('living room', 'гостиная'), w('bedroom', 'спальня'),
      w('dining room', 'столовая', 'noun', 2), w('garage', 'гараж'),
      w('roof', 'крыша'), w('stairs', 'лестница', 'noun', 2),
      w('upstairs', 'наверху', 'adverb'), w('downstairs', 'внизу', 'adverb'),
      w('fridge', 'холодильник'), w('cooker', 'плита'),
      w('bath', 'ванна'), w('shower', 'душ'),
      w('armchair', 'кресло', 'noun', 2), w('fireplace', 'камин', 'noun', 2),
    ],
    phrases: [
      { phrase: 'There are two bedrooms in my house.', translation: 'В моём доме две спальни.', context: 'Описание дома' },
      { phrase: 'Is there a garden?', translation: 'Есть ли сад?', context: 'Вопрос' },
      { phrase: 'Yes, there is. / No, there isn\'t.', translation: 'Да. / Нет.', context: 'Ответ' },
    ],
    sentences: [
      { sentence: 'My house has got three bedrooms and a big kitchen.', translation: 'В моём доме три спальни и большая кухня.', highlightWords: ['house', 'bedrooms', 'kitchen'] },
      { sentence: 'There is a bath and a shower in the bathroom.', translation: 'В ванной есть ванна и душ.', highlightWords: ['There is', 'bath', 'shower'] },
      { sentence: 'The living room is downstairs.', translation: 'Гостиная на первом этаже.', highlightWords: ['living room', 'downstairs'] },
    ],
    grammar: ['There is a... / There are two...', 'Is there...? / Are there...?', 'upstairs / downstairs'],
    texts: [
      {
        title: 'Our New House',
        titleRu: 'Наш новый дом',
        lines: [
          'We have got a new house and it is very big.',
          'There are three bedrooms and a bathroom upstairs.',
          'My bedroom is next to my brother\'s bedroom.',
          'Downstairs there is a large kitchen with a fridge and a cooker.',
          'The living room is downstairs too with a sofa and a fireplace.',
          'There is also a dining room where we have dinner.',
          'We have got a garage for our car next to the house.',
          'I like our new house because my room is very big.',
        ],
      },
    ],
  },
  {
    id: 's3_a_day_off',
    title: 'Module 7: A Day Off!',
    titleRu: 'Модуль 7: Выходной!',
    grade: 3,
    order: 6,
    words: [
      w('morning', 'утро'), w('afternoon', 'день'), w('evening', 'вечер'),
      w('night', 'ночь'), w('today', 'сегодня', 'adverb'),
      w('weekend', 'выходные'), w('holiday', 'каникулы/праздник'),
      w('get up', 'встать', 'verb'), w('have breakfast', 'завтракать', 'verb'),
      w('go to school', 'идти в школу', 'verb'),
      w('come home', 'прийти домой', 'verb'),
      w('do homework', 'делать уроки', 'verb'),
      w('watch TV', 'смотреть ТВ', 'verb'),
      w('go to bed', 'ложиться спать', 'verb'),
      w('have dinner', 'обедать/ужинать', 'verb'),
      w('play games', 'играть в игры', 'verb'),
      w('read books', 'читать книги', 'verb'),
      w('have fun', 'веселиться', 'verb'),
    ],
    phrases: [
      { phrase: 'I get up at seven o\'clock.', translation: 'Я встаю в семь часов.', context: 'Распорядок' },
      { phrase: 'What do you do in the morning?', translation: 'Что ты делаешь утром?', context: 'Вопрос' },
      { phrase: 'On Saturdays I play football.', translation: 'По субботам я играю в футбол.', context: 'Выходные' },
    ],
    sentences: [
      { sentence: 'I get up at seven and have breakfast.', translation: 'Я встаю в семь и завтракаю.', highlightWords: ['get up', 'seven', 'have breakfast'] },
      { sentence: 'In the afternoon I do my homework.', translation: 'Днём я делаю уроки.', highlightWords: ['afternoon', 'do', 'homework'] },
      { sentence: 'At the weekend I play with my friends.', translation: 'В выходные я играю с друзьями.', highlightWords: ['weekend', 'play', 'friends'] },
    ],
    grammar: ['Present Simple для распорядка дня', 'at + время (at 7 o\'clock)', 'in the morning / afternoon / evening'],
    texts: [
      {
        title: 'My Saturday',
        titleRu: 'Моя суббота',
        lines: [
          'Today is Saturday and it is my day off.',
          'I get up late in the morning because there is no school.',
          'I have breakfast with my family at nine o\'clock.',
          'In the morning I watch cartoons and play games.',
          'In the afternoon my friends come home and we play football.',
          'After that we come home and have dinner together.',
          'In the evening I read books and watch TV.',
          'I go to bed at nine o\'clock because I am tired but happy.',
        ],
      },
    ],
  },
  {
    id: 's3_day_by_day',
    title: 'Module 8: Day by Day!',
    titleRu: 'Модуль 8: День за днём!',
    grade: 3,
    order: 7,
    words: [
      w('Monday', 'понедельник'), w('Tuesday', 'вторник'),
      w('Wednesday', 'среда', 'noun', 2), w('Thursday', 'четверг'),
      w('Friday', 'пятница'), w('Saturday', 'суббота'),
      w('Sunday', 'воскресенье'), w('week', 'неделя'),
      w('o\'clock', 'часов', 'noun', 2), w('half past', 'половина', 'phrase', 2),
      w('quarter past', 'четверть', 'phrase', 2), w('quarter to', 'без четверти', 'phrase', 2),
      w('early', 'рано', 'adverb'), w('late', 'поздно', 'adverb'),
      w('time', 'время'), w('breakfast', 'завтрак'),
      w('lunch', 'обед'), w('dinner', 'ужин'),
      w('always', 'всегда', 'adverb'), w('usually', 'обычно', 'adverb'),
      w('sometimes', 'иногда', 'adverb'), w('never', 'никогда', 'adverb'),
    ],
    phrases: [
      { phrase: 'What time is it?', translation: 'Который час?', context: 'Время' },
      { phrase: 'It\'s half past eight.', translation: 'Половина девятого.', context: 'Время' },
      { phrase: 'I always have lunch at school.', translation: 'Я всегда обедаю в школе.', context: 'Привычки' },
      { phrase: 'What day is it today?', translation: 'Какой сегодня день?', context: 'Дни недели' },
    ],
    sentences: [
      { sentence: 'On Monday I have English and Maths.', translation: 'В понедельник у меня английский и математика.', highlightWords: ['Monday', 'English', 'Maths'] },
      { sentence: 'I usually get up at half past seven.', translation: 'Я обычно встаю в половину восьмого.', highlightWords: ['usually', 'get up', 'half past'] },
      { sentence: 'We never go to school on Sunday.', translation: 'Мы никогда не ходим в школу в воскресенье.', highlightWords: ['never', 'go', 'Sunday'] },
    ],
    grammar: ['Дни недели (с заглавной буквы!)', 'What time is it? — It\'s ... o\'clock / half past / quarter past/to', 'Adverbs of frequency: always, usually, sometimes, never'],
    texts: [
      {
        title: 'My Week',
        titleRu: 'Моя неделя',
        lines: [
          'I always get up early on Monday because I have school.',
          'I usually have breakfast at half past seven.',
          'On Tuesday and Thursday I have English lessons.',
          'On Wednesday I sometimes go to the park after school.',
          'I always have lunch at quarter past twelve at school.',
          'On Friday I am usually happy because the weekend is coming.',
          'On Saturday I never get up early and I have fun all day.',
          'Sunday is my favourite day because I play with my family.',
        ],
      },
    ],
  },
];
