// Syllable dictionary for word-by-word reading
// Each word maps to its syllable breakdown

export const SYLLABLES: Record<string, string[]> = {
  // ===== 1 SYLLABLE =====
  cat: ['cat'],
  dog: ['dog'],
  fish: ['fish'],
  bird: ['bird'],
  frog: ['frog'],
  horse: ['horse'],
  bear: ['bear'],
  hat: ['hat'],
  coat: ['coat'],
  shoes: ['shoes'],
  boots: ['boots'],
  dress: ['dress'],
  shorts: ['shorts'],
  sun: ['sun'],
  tree: ['tree'],
  sea: ['sea'],
  beach: ['beach'],
  park: ['park'],
  rain: ['rain'],
  snow: ['snow'],
  moon: ['moon'],
  star: ['star'],
  ball: ['ball'],
  doll: ['doll'],
  car: ['car'],
  bike: ['bike'],
  train: ['train'],
  boat: ['boat'],
  kite: ['kite'],
  toy: ['toy'],
  drum: ['drum'],
  game: ['game'],
  book: ['book'],
  pen: ['pen'],
  desk: ['desk'],
  red: ['red'],
  blue: ['blue'],
  green: ['green'],
  black: ['black'],
  white: ['white'],
  brown: ['brown'],
  pink: ['pink'],
  big: ['big'],
  small: ['small'],
  tall: ['tall'],
  short: ['short'],
  old: ['old'],
  new: ['new'],
  hot: ['hot'],
  cold: ['cold'],
  dark: ['dark'],
  fair: ['fair'],
  long: ['long'],
  run: ['run'],
  jump: ['jump'],
  swim: ['swim'],
  dance: ['dance'],
  sing: ['sing'],
  fly: ['fly'],
  read: ['read'],
  write: ['write'],
  draw: ['draw'],
  cook: ['cook'],
  eat: ['eat'],
  drink: ['drink'],
  sleep: ['sleep'],
  play: ['play'],
  climb: ['climb'],
  walk: ['walk'],
  help: ['help'],
  look: ['look'],
  want: ['want'],
  come: ['come'],
  love: ['love'],
  like: ['like'],
  see: ['see'],
  go: ['go'],
  put: ['put'],
  take: ['take'],
  head: ['head'],
  arm: ['arm'],
  leg: ['leg'],
  hand: ['hand'],
  foot: ['foot'],
  eye: ['eye'],
  ear: ['ear'],
  nose: ['nose'],
  mouth: ['mouth'],
  hair: ['hair'],
  face: ['face'],
  cake: ['cake'],
  milk: ['milk'],
  juice: ['juice'],
  egg: ['egg'],
  bread: ['bread'],
  cheese: ['cheese'],
  house: ['house'],
  home: ['home'],
  bed: ['bed'],
  door: ['door'],
  lamp: ['lamp'],
  wall: ['wall'],
  floor: ['floor'],
  roof: ['roof'],
  boy: ['boy'],
  girl: ['girl'],
  mum: ['mum'],
  dad: ['dad'],
  friend: ['friend'],
  clown: ['clown'],
  king: ['king'],
  queen: ['queen'],
  one: ['one'],
  two: ['two'],
  three: ['three'],
  four: ['four'],
  five: ['five'],
  six: ['six'],
  eight: ['eight'],
  nine: ['nine'],
  ten: ['ten'],
  shelf: ['shelf'],
  near: ['near'],
  spring: ['spring'],
  socks: ['socks'],
  jeans: ['jeans'],
  skirt: ['skirt'],

  // ===== 2 SYLLABLES =====
  rabbit: ['rab', 'bit'],
  hamster: ['ham', 'ster'],
  parrot: ['par', 'rot'],
  puppy: ['pup', 'py'],
  kitten: ['kit', 'ten'],
  monkey: ['mon', 'key'],
  lion: ['li', 'on'],
  tiger: ['ti', 'ger'],
  table: ['ta', 'ble'],
  chair: ['chair'],
  window: ['win', 'dow'],
  mirror: ['mir', 'ror'],
  sofa: ['so', 'fa'],
  garden: ['gar', 'den'],
  kitchen: ['kitch', 'en'],
  bedroom: ['bed', 'room'],
  bathroom: ['bath', 'room'],
  pencil: ['pen', 'cil'],
  ruler: ['ru', 'ler'],
  teacher: ['teach', 'er'],
  lesson: ['les', 'son'],
  yellow: ['yel', 'low'],
  orange: ['or', 'ange'],
  purple: ['pur', 'ple'],
  present: ['pres', 'ent'],
  happy: ['hap', 'py'],
  funny: ['fun', 'ny'],
  clever: ['clev', 'er'],
  scary: ['sca', 'ry'],
  friendly: ['friend', 'ly'],
  little: ['lit', 'tle'],
  sunny: ['sun', 'ny'],
  windy: ['win', 'dy'],
  rainy: ['rai', 'ny'],
  raining: ['rain', 'ing'],
  island: ['is', 'land'],
  magic: ['ma', 'gic'],
  pretty: ['pret', 'ty'],
  lovely: ['love', 'ly'],
  ready: ['read', 'y'],
  today: ['to', 'day'],
  party: ['par', 'ty'],
  children: ['chil', 'dren'],
  baby: ['ba', 'by'],
  sister: ['sis', 'ter'],
  brother: ['broth', 'er'],
  woman: ['wom', 'an'],
  nanny: ['nan', 'ny'],
  circus: ['cir', 'cus'],
  puppet: ['pup', 'pet'],
  robot: ['ro', 'bot'],
  puzzle: ['puz', 'zle'],
  guitar: ['gui', 'tar'],
  piano: ['pi', 'an', 'o'],
  sandwich: ['sand', 'wich'],
  apple: ['ap', 'ple'],
  pizza: ['piz', 'za'],
  water: ['wa', 'ter'],
  candy: ['can', 'dy'],
  biscuit: ['bis', 'cuit'],
  jacket: ['jack', 'et'],
  'tshirt': ['t', 'shirt'],
  't-shirt': ['t', 'shirt'],
  trumpet: ['trum', 'pet'],
  summer: ['sum', 'mer'],
  winter: ['win', 'ter'],
  autumn: ['au', 'tumn'],
  people: ['peo', 'ple'],
  morning: ['morn', 'ing'],
  evening: ['eve', 'ning'],
  welcome: ['wel', 'come'],
  open: ['o', 'pen'],
  under: ['un', 'der'],
  behind: ['be', 'hind'],
  music: ['mu', 'sic'],
  flowers: ['flow', 'ers'],
  seven: ['sev', 'en'],
  homework: ['home', 'work'],
  breakfast: ['break', 'fast'],
  dinner: ['din', 'ner'],

  // ===== 3 SYLLABLES =====
  elephant: ['el', 'e', 'phant'],
  ballerina: ['bal', 'le', 'ri', 'na'],
  kangaroo: ['kan', 'ga', 'roo'],
  umbrella: ['um', 'brel', 'la'],
  banana: ['ba', 'na', 'na'],
  chocolate: ['choc', 'late'],
  butterfly: ['but', 'ter', 'fly'],
  bicycle: ['bi', 'cy', 'cle'],
  beautiful: ['beau', 'ti', 'ful'],
  wonderful: ['won', 'der', 'ful'],
  holiday: ['hol', 'i', 'day'],
  magician: ['ma', 'gi', 'cian'],
  afternoon: ['af', 'ter', 'noon'],
  computer: ['com', 'pu', 'ter'],
  lemonade: ['lem', 'on', 'ade'],
  watermelon: ['wa', 'ter', 'mel', 'on'],
  grandmother: ['grand', 'moth', 'er'],
  grandfather: ['grand', 'fa', 'ther'],
  family: ['fam', 'i', 'ly'],
  animal: ['an', 'i', 'mal'],
  favourite: ['fav', 'our', 'ite'],
  favorite: ['fav', 'or', 'ite'],
  yesterday: ['yes', 'ter', 'day'],
  basketball: ['bas', 'ket', 'ball'],
  telephone: ['tel', 'e', 'phone'],
  crocodile: ['croc', 'o', 'dile'],
  together: ['to', 'geth', 'er'],
  everyone: ['ev', 'ery', 'one'],
  tomorrow: ['to', 'mor', 'row'],
  adventure: ['ad', 'ven', 'ture'],
  dangerous: ['dan', 'ger', 'ous'],

  // ===== 4+ SYLLABLES =====
  everybody: ['ev', 'ery', 'bod', 'y'],
  alligator: ['al', 'li', 'ga', 'tor'],
  caterpillar: ['cat', 'er', 'pil', 'lar'],
  hippopotamus: ['hip', 'po', 'pot', 'a', 'mus'],

  // ===== OTHER WORDS & -ING FORMS =====
  teddy: ['ted', 'dy'],
  chuckles: ['chuck', 'les'],
  cherry: ['cher', 'ry'],
  soldier: ['sol', 'dier'],
  different: ['dif', 'fer', 'ent'],
  wearing: ['wear', 'ing'],
  playing: ['play', 'ing'],
  swimming: ['swim', 'ming'],
  dancing: ['danc', 'ing'],
  singing: ['sing', 'ing'],
  running: ['run', 'ning'],
  jumping: ['jump', 'ing'],
  climbing: ['climb', 'ing'],
  reading: ['read', 'ing'],
  writing: ['writ', 'ing'],
  cooking: ['cook', 'ing'],
  eating: ['eat', 'ing'],
  sleeping: ['sleep', 'ing'],

  // ===== SPOTLIGHT 2-3 ADDITIONS =====
  // Adjectives
  terrible: ['ter', 'ri', 'ble'],
  sorry: ['sor', 'ry'],
  cloudy: ['clou', 'dy'],
  snowy: ['sno', 'wy'],

  // Prepositions & adverbs
  over: ['o', 'ver'],
  between: ['be', 'tween'],
  another: ['an', 'oth', 'er'],
  outside: ['out', 'side'],
  inside: ['in', 'side'],
  upstairs: ['up', 'stairs'],
  downstairs: ['down', 'stairs'],
  about: ['a', 'bout'],
  after: ['af', 'ter'],
  before: ['be', 'fore'],
  again: ['a', 'gain'],
  because: ['be', 'cause'],
  other: ['oth', 'er'],
  also: ['al', 'so'],
  only: ['on', 'ly'],
  very: ['ver', 'y'],
  really: ['re', 'al', 'ly'],
  quickly: ['quick', 'ly'],
  slowly: ['slow', 'ly'],
  loudly: ['loud', 'ly'],
  sometimes: ['some', 'times'],
  always: ['al', 'ways'],
  usually: ['u', 'su', 'al', 'ly'],
  never: ['nev', 'er'],
  often: ['of', 'ten'],
  everything: ['ev', 'ery', 'thing'],

  // Family
  mother: ['moth', 'er'],
  father: ['fa', 'ther'],
  grandma: ['grand', 'ma'],
  grandpa: ['grand', 'pa'],
  cousin: ['cou', 'sin'],
  uncle: ['un', 'cle'],

  // Days of the week
  monday: ['Mon', 'day'],
  tuesday: ['Tues', 'day'],
  wednesday: ['Wednes', 'day'],
  thursday: ['Thurs', 'day'],
  friday: ['Fri', 'day'],
  saturday: ['Sat', 'ur', 'day'],
  sunday: ['Sun', 'day'],

  // Time & seasons
  weather: ['weath', 'er'],
  springtime: ['spring', 'time'],
  flower: ['flow', 'er'],

  // School
  eraser: ['e', 'ra', 'ser'],
  english: ['Eng', 'lish'],
  science: ['sci', 'ence'],
  number: ['num', 'ber'],
  letter: ['let', 'ter'],
  colour: ['col', 'our'],

  // Food & party
  birthday: ['birth', 'day'],
  balloon: ['bal', 'loon'],
  candle: ['can', 'dle'],
  matter: ['mat', 'ter'],

  // Home
  living: ['liv', 'ing'],
  cupboard: ['cup', 'board'],
  wardrobe: ['ward', 'robe'],
  bookcase: ['book', 'case'],
  fireplace: ['fire', 'place'],
  carpet: ['car', 'pet'],

  // Animals
  tortoise: ['tor', 'toise'],
  giraffe: ['gi', 'raffe'],
  dolphin: ['dol', 'phin'],
  seahorse: ['sea', 'horse'],
  goldfish: ['gold', 'fish'],
  // ===== ALL SPOTLIGHT 2-3 WORDS =====
  // 1-syllable (must be in dict so getSyllables finds them)
  arms: ['arms'], aunt: ['aunt'], bath: ['bath'], beak: ['beak'],
  bear: ['bear'], bike: ['bike'], bird: ['bird'], black: ['black'],
  blue: ['blue'], boat: ['boat'], book: ['book'], books: ['books'],
  brave: ['brave'], brown: ['brown'], cake: ['cake'], camp: ['camp'],
  chair: ['chair'], chimp: ['chimp'], climb: ['climb'], clown: ['clown'],
  coat: ['coat'], cold: ['cold'], come: ['come'], cook: ['cook'],
  count: ['count'], cream: ['cream'], cute: ['cute'], dance: ['dance'],
  dark: ['dark'], desk: ['desk'], doll: ['doll'], door: ['door'],
  draw: ['draw'], drink: ['drink'], drum: ['drum'], ears: ['ears'],
  eight: ['eight'], eyes: ['eyes'], face: ['face'], fair: ['fair'],
  feet: ['feet'], film: ['film'], fish: ['fish'], five: ['five'],
  flag: ['flag'], flat: ['flat'], floor: ['floor'], four: ['four'],
  frog: ['frog'], front: ['front'], fruit: ['fruit'], game: ['game'],
  games: ['games'], girl: ['girl'], glass: ['glass'], green: ['green'],
  hair: ['hair'], half: ['half'], hands: ['hands'], have: ['have'],
  head: ['head'], home: ['home'], horse: ['horse'], house: ['house'],
  jeans: ['jeans'], juice: ['juice'], jump: ['jump'], kind: ['kind'],
  kite: ['kite'], knees: ['knees'], lake: ['lake'], lamp: ['lamp'],
  late: ['late'], legs: ['legs'], like: ['like'], long: ['long'],
  love: ['love'], lunch: ['lunch'], make: ['make'], milk: ['milk'],
  mouse: ['mouse'], mouth: ['mouth'], near: ['near'], nest: ['nest'],
  next: ['next'], night: ['night'], nine: ['nine'], nose: ['nose'],
  paint: ['paint'], park: ['park'], past: ['past'], pink: ['pink'],
  play: ['play'], pool: ['pool'], queen: ['queen'], read: ['read'],
  ride: ['ride'], roof: ['roof'], room: ['room'], school: ['school'],
  seal: ['seal'], shelf: ['shelf'], shoes: ['shoes'], short: ['short'],
  shorts: ['shorts'], sing: ['sing'], skirt: ['skirt'], sleep: ['sleep'],
  small: ['small'], snake: ['snake'], socks: ['socks'], spring: ['spring'],
  stairs: ['stairs'], strong: ['strong'], swim: ['swim'], swing: ['swing'],
  tail: ['tail'], tall: ['tall'], teeth: ['teeth'], their: ['their'],
  three: ['three'], time: ['time'], toes: ['toes'], tree: ['tree'],
  vest: ['vest'], wake: ['wake'], wall: ['wall'], watch: ['watch'],
  week: ['week'], white: ['white'], wing: ['wing'], write: ['write'],
  yacht: ['yacht'], young: ['young'], your: ['your'],
  body: ['bod', 'y'], story: ['sto', 'ry'],

  // 2-syllable missing
  amazing: ['a', 'ma', 'zing'], armchair: ['arm', 'chair'],
  cartoon: ['car', 'toon'], classroom: ['class', 'room'],
  cooker: ['cook', 'er'], dining: ['di', 'ning'],
  early: ['ear', 'ly'], feather: ['feath', 'er'],
  football: ['foot', 'ball'], forest: ['for', 'est'],
  fridge: ['fridge'], garage: ['ga', 'rage'],
  jelly: ['jel', 'ly'], listen: ['lis', 'ten'],
  maths: ['maths'], mountain: ['moun', 'tain'],
  picture: ['pic', 'ture'], playground: ['play', 'ground'],
  pupil: ['pu', 'pil'], quarter: ['quar', 'ter'],
  radio: ['ra', 'di', 'o'], river: ['riv', 'er'],
  rocking: ['rock', 'ing'], shower: ['show', 'er'],
  shoulders: ['shoul', 'ders'], tennis: ['ten', 'nis'],
  tummy: ['tum', 'my'], weekend: ['week', 'end'],
  vegetables: ['veg', 'ta', 'bles'],
  'jack-in-the-box': ['jack', 'in', 'the', 'box'],
  "o'clock": ["o'", 'clock'],
};

export function getSyllables(word: string): string[] {
  const clean = word.toLowerCase().replace(/[.,!?;:'"()]/g, '');
  if (!clean) return [word];
  if (SYLLABLES[clean]) return SYLLABLES[clean];
  // No auto-split — unknown words shown as-is (prevents garbage like "s·old·ier")
  return [clean];
}
