// Syllable dictionary for word-by-word reading
// Each word maps to its syllable breakdown

export const SYLLABLES: Record<string, string[]> = {
  // ===== 1 SYLLABLE =====
  cat: ['cat'],
  dog: ['dog'],
  fish: ['fish'],
  bird: ['bird'],
  frog: ['frog'],
  horse: ['horse'],
  bear: ['bear'],
  hat: ['hat'],
  coat: ['coat'],
  shoes: ['shoes'],
  boots: ['boots'],
  dress: ['dress'],
  shorts: ['shorts'],
  sun: ['sun'],
  tree: ['tree'],
  sea: ['sea'],
  beach: ['beach'],
  park: ['park'],
  rain: ['rain'],
  snow: ['snow'],
  moon: ['moon'],
  star: ['star'],
  ball: ['ball'],
  doll: ['doll'],
  car: ['car'],
  bike: ['bike'],
  train: ['train'],
  boat: ['boat'],
  kite: ['kite'],
  toy: ['toy'],
  drum: ['drum'],
  game: ['game'],
  book: ['book'],
  pen: ['pen'],
  desk: ['desk'],
  red: ['red'],
  blue: ['blue'],
  green: ['green'],
  black: ['black'],
  white: ['white'],
  brown: ['brown'],
  pink: ['pink'],
  big: ['big'],
  small: ['small'],
  tall: ['tall'],
  short: ['short'],
  old: ['old'],
  new: ['new'],
  hot: ['hot'],
  cold: ['cold'],
  dark: ['dark'],
  fair: ['fair'],
  long: ['long'],
  run: ['run'],
  jump: ['jump'],
  swim: ['swim'],
  dance: ['dance'],
  sing: ['sing'],
  fly: ['fly'],
  read: ['read'],
  write: ['write'],
  draw: ['draw'],
  cook: ['cook'],
  eat: ['eat'],
  drink: ['drink'],
  sleep: ['sleep'],
  play: ['play'],
  climb: ['climb'],
  walk: ['walk'],
  help: ['help'],
  look: ['look'],
  want: ['want'],
  come: ['come'],
  love: ['love'],
  like: ['like'],
  see: ['see'],
  go: ['go'],
  put: ['put'],
  take: ['take'],
  head: ['head'],
  arm: ['arm'],
  leg: ['leg'],
  hand: ['hand'],
  foot: ['foot'],
  eye: ['eye'],
  ear: ['ear'],
  nose: ['nose'],
  mouth: ['mouth'],
  hair: ['hair'],
  face: ['face'],
  cake: ['cake'],
  milk: ['milk'],
  juice: ['juice'],
  egg: ['egg'],
  bread: ['bread'],
  cheese: ['cheese'],
  house: ['house'],
  home: ['home'],
  bed: ['bed'],
  door: ['door'],
  lamp: ['lamp'],
  wall: ['wall'],
  floor: ['floor'],
  roof: ['roof'],
  boy: ['boy'],
  girl: ['girl'],
  mum: ['mum'],
  dad: ['dad'],
  friend: ['friend'],
  clown: ['clown'],
  king: ['king'],
  queen: ['queen'],
  one: ['one'],
  two: ['two'],
  three: ['three'],
  four: ['four'],
  five: ['five'],
  six: ['six'],
  eight: ['eight'],
  nine: ['nine'],
  ten: ['ten'],
  shelf: ['shelf'],
  near: ['near'],
  spring: ['spring'],
  socks: ['socks'],
  jeans: ['jeans'],
  skirt: ['skirt'],

  // ===== 2 SYLLABLES =====
  rabbit: ['rab', 'bit'],
  hamster: ['ham', 'ster'],
  parrot: ['par', 'rot'],
  puppy: ['pup', 'py'],
  kitten: ['kit', 'ten'],
  monkey: ['mon', 'key'],
  lion: ['li', 'on'],
  tiger: ['ti', 'ger'],
  table: ['ta', 'ble'],
  chair: ['chair'],
  window: ['win', 'dow'],
  mirror: ['mir', 'ror'],
  sofa: ['so', 'fa'],
  garden: ['gar', 'den'],
  kitchen: ['kitch', 'en'],
  bedroom: ['bed', 'room'],
  bathroom: ['bath', 'room'],
  pencil: ['pen', 'cil'],
  ruler: ['ru', 'ler'],
  teacher: ['teach', 'er'],
  lesson: ['les', 'son'],
  yellow: ['yel', 'low'],
  orange: ['or', 'ange'],
  purple: ['pur', 'ple'],
  present: ['pres', 'ent'],
  happy: ['hap', 'py'],
  funny: ['fun', 'ny'],
  clever: ['clev', 'er'],
  scary: ['scar', 'y'],
  friendly: ['friend', 'ly'],
  little: ['lit', 'tle'],
  sunny: ['sun', 'ny'],
  windy: ['win', 'dy'],
  rainy: ['rain', 'y'],
  raining: ['rain', 'ing'],
  island: ['is', 'land'],
  magic: ['mag', 'ic'],
  pretty: ['pret', 'ty'],
  lovely: ['love', 'ly'],
  ready: ['read', 'y'],
  today: ['to', 'day'],
  party: ['par', 'ty'],
  children: ['chil', 'dren'],
  baby: ['ba', 'by'],
  sister: ['sis', 'ter'],
  brother: ['broth', 'er'],
  woman: ['wom', 'an'],
  nanny: ['nan', 'ny'],
  circus: ['cir', 'cus'],
  puppet: ['pup', 'pet'],
  robot: ['ro', 'bot'],
  puzzle: ['puz', 'zle'],
  guitar: ['gui', 'tar'],
  piano: ['pi', 'ano'],
  sandwich: ['sand', 'wich'],
  apple: ['ap', 'ple'],
  pizza: ['piz', 'za'],
  water: ['wa', 'ter'],
  candy: ['can', 'dy'],
  biscuit: ['bis', 'cuit'],
  jacket: ['jack', 'et'],
  'tshirt': ['t', 'shirt'],
  't-shirt': ['t', 'shirt'],
  trumpet: ['trum', 'pet'],
  summer: ['sum', 'mer'],
  winter: ['win', 'ter'],
  autumn: ['au', 'tumn'],
  people: ['peo', 'ple'],
  morning: ['morn', 'ing'],
  evening: ['eve', 'ning'],
  welcome: ['wel', 'come'],
  open: ['o', 'pen'],
  under: ['un', 'der'],
  behind: ['be', 'hind'],
  music: ['mu', 'sic'],
  flowers: ['flow', 'ers'],
  seven: ['sev', 'en'],
  homework: ['home', 'work'],
  breakfast: ['break', 'fast'],
  dinner: ['din', 'ner'],

  // ===== 3 SYLLABLES =====
  elephant: ['el', 'e', 'phant'],
  ballerina: ['bal', 'le', 'ri', 'na'],
  kangaroo: ['kan', 'ga', 'roo'],
  umbrella: ['um', 'brel', 'la'],
  banana: ['ba', 'na', 'na'],
  chocolate: ['choc', 'o', 'late'],
  butterfly: ['but', 'ter', 'fly'],
  bicycle: ['bi', 'cy', 'cle'],
  beautiful: ['beau', 'ti', 'ful'],
  wonderful: ['won', 'der', 'ful'],
  holiday: ['hol', 'i', 'day'],
  magician: ['ma', 'gi', 'cian'],
  afternoon: ['af', 'ter', 'noon'],
  computer: ['com', 'pu', 'ter'],
  lemonade: ['lem', 'on', 'ade'],
  watermelon: ['wa', 'ter', 'mel', 'on'],
  grandmother: ['grand', 'moth', 'er'],
  grandfather: ['grand', 'fa', 'ther'],
  family: ['fam', 'i', 'ly'],
  animal: ['an', 'i', 'mal'],
  favourite: ['fa', 'vour', 'ite'],
  favorite: ['fa', 'vor', 'ite'],
  yesterday: ['yes', 'ter', 'day'],
  basketball: ['bas', 'ket', 'ball'],
  telephone: ['tel', 'e', 'phone'],
  crocodile: ['croc', 'o', 'dile'],
  together: ['to', 'geth', 'er'],
  everyone: ['ev', 'ery', 'one'],
  tomorrow: ['to', 'mor', 'row'],
  adventure: ['ad', 'ven', 'ture'],
  dangerous: ['dan', 'ger', 'ous'],

  // ===== 4+ SYLLABLES =====
  everybody: ['ev', 'ery', 'bod', 'y'],
  alligator: ['al', 'li', 'ga', 'tor'],
  caterpillar: ['cat', 'er', 'pil', 'lar'],
  hippopotamus: ['hip', 'po', 'pot', 'a', 'mus'],
};

export function getSyllables(word: string): string[] {
  const clean = word.toLowerCase().replace(/[.,!?;:'"()]/g, '');
  if (SYLLABLES[clean]) return SYLLABLES[clean];
  // Fallback: return whole word as single syllable
  return [clean];
}
